import {
  sdsEntries,
  inventoryItems,
  employees,
  trainingCourses,
  auditLog,
  shopInfo,
  programVersionHistory,
  nonRoutineTasks,
  ghsPictogramLabels,
  getEmployeeTrainingStats,
  getComplianceData,
} from "./data";

// Dynamic import to avoid SSR issues
async function loadJsPDF() {
  const jsPDFModule = await import("jspdf");
  const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
  await import("jspdf-autotable");
  return jsPDF;
}

const NAVY = [11, 20, 38] as const;
const WHITE = [255, 255, 255] as const;
const GRAY = [120, 130, 145] as const;


function addHeader(doc: InstanceType<typeof import("jspdf").jsPDF>, title: string) {
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 22, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 15);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(shopInfo.name, doc.internal.pageSize.getWidth() - 14, 15, { align: "right" });
  doc.setTextColor(0, 0, 0);
}

function addFooter(doc: InstanceType<typeof import("jspdf").jsPDF>) {
  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(`Generated by ShieldSDS on ${new Date().toLocaleDateString()}`, 14, h - 8);
    doc.text(`Page ${i} of ${pageCount}`, w - 14, h - 8, { align: "right" });
  }
}

function autoTable(doc: InstanceType<typeof import("jspdf").jsPDF>, opts: Record<string, unknown>) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (doc as any).autoTable(opts);
}

function getFinalY(doc: InstanceType<typeof import("jspdf").jsPDF>): number {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (doc as any).lastAutoTable?.finalY || 30;
}

// ─── 1. Inspection Packet PDF ─────────────────────────────────────────────────

export async function generateInspectionPacketPDF() {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();

  // Page 1: Cover
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 297, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text("OSHA HazCom", w / 2, 80, { align: "center" });
  doc.text("Compliance Packet", w / 2, 96, { align: "center" });
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(shopInfo.name, w / 2, 120, { align: "center" });
  doc.text(`${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 130, { align: "center" });
  doc.text(shopInfo.phone, w / 2, 140, { align: "center" });
  doc.setFontSize(12);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`, w / 2, 165, { align: "center" });
  const compliance = getComplianceData();
  doc.setFontSize(48);
  doc.setFont("helvetica", "bold");
  const scoreColor = compliance.score >= 90 ? [34, 197, 94] : compliance.score >= 70 ? [245, 158, 11] : [239, 68, 68];
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(`${compliance.score}%`, w / 2, 200, { align: "center" });
  doc.setFontSize(12);
  doc.text("Compliance Score", w / 2, 212, { align: "center" });

  // Page 2: HazCom Program Summary
  doc.addPage();
  addHeader(doc, "HazCom Program Summary");
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  let y = 32;
  doc.setFont("helvetica", "bold");
  doc.text("Responsible Person:", 14, y);
  doc.setFont("helvetica", "normal");
  doc.text(`${shopInfo.owner} — ${shopInfo.ownerPhone}`, 60, y);
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.text("Program Version:", 14, y);
  doc.setFont("helvetica", "normal");
  doc.text(`${programVersionHistory[0].version} (${programVersionHistory[0].date})`, 60, y);
  y += 12;
  doc.setFont("helvetica", "bold");
  doc.text("Program Sections:", 14, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  const sections = [
    "1. Purpose and Scope", "2. Responsible Person", "3. Chemical Inventory",
    "4. SDS Access", "5. Labeling System", "6. Employee Training",
    "7. Non-Routine Tasks", "8. Contractor Communication",
    "9. Emergency Procedures", "10. Program Review",
  ];
  sections.forEach((s) => { doc.text(s, 20, y); y += 6; });

  // Page 3: Chemical Inventory Table
  doc.addPage();
  addHeader(doc, "Chemical Inventory");
  autoTable(doc, {
    startY: 28,
    head: [["#", "Product Name", "Manufacturer", "Location", "Signal Word", "SDS Status"]],
    body: sdsEntries.map((s, i) => [
      i + 1,
      s.productName,
      s.manufacturer,
      s.storageLocation,
      s.signalWord,
      s.sdsStatus.charAt(0).toUpperCase() + s.sdsStatus.slice(1),
    ]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14 },
  });

  // Page 4: SDS Coverage Stats
  doc.addPage();
  addHeader(doc, "SDS Coverage");
  const currentSDS = sdsEntries.filter((s) => s.sdsStatus === "current").length;
  const reviewSDS = sdsEntries.filter((s) => s.sdsStatus === "review").length;
  const missingSDS = sdsEntries.filter((s) => s.sdsStatus === "missing").length;
  y = 34;
  doc.setFontSize(11);
  doc.text(`Total SDS Entries: ${sdsEntries.length}`, 14, y); y += 8;
  doc.text(`Current: ${currentSDS}`, 14, y); y += 6;
  doc.text(`Needs Review: ${reviewSDS}`, 14, y); y += 6;
  doc.text(`Missing: ${missingSDS}`, 14, y); y += 6;
  doc.text(`Coverage: ${Math.round((currentSDS / sdsEntries.length) * 100)}%`, 14, y); y += 12;
  if (missingSDS > 0) {
    doc.setFont("helvetica", "bold");
    doc.text("Missing SDS:", 14, y);
    doc.setFont("helvetica", "normal");
    y += 6;
    sdsEntries.filter((s) => s.sdsStatus === "missing").forEach((s) => {
      doc.text(`- ${s.productName} (${s.manufacturer}) — ${s.storageLocation}`, 20, y);
      y += 6;
    });
  }

  // Page 5: Label Compliance
  doc.addPage();
  addHeader(doc, "Label Compliance");
  const totalContainers = inventoryItems.reduce((sum, i) => sum + i.containers, 0);
  const labeledContainers = inventoryItems.filter((i) => i.labeled).reduce((sum, i) => sum + i.containers, 0);
  y = 34;
  doc.setFontSize(11);
  doc.text(`Total Containers: ${totalContainers}`, 14, y); y += 8;
  doc.text(`Labeled: ${labeledContainers}`, 14, y); y += 6;
  doc.text(`Unlabeled: ${totalContainers - labeledContainers}`, 14, y); y += 6;
  doc.text(`Compliance: ${totalContainers > 0 ? Math.round((labeledContainers / totalContainers) * 100) : 100}%`, 14, y); y += 12;
  const locations = Array.from(new Set(inventoryItems.map((i) => i.location)));
  autoTable(doc, {
    startY: y,
    head: [["Location", "Chemicals", "Containers", "Labeled"]],
    body: locations.map((loc) => {
      const items = inventoryItems.filter((i) => i.location === loc);
      const containers = items.reduce((sum, i) => sum + i.containers, 0);
      const labeled = items.filter((i) => i.labeled).reduce((sum, i) => sum + i.containers, 0);
      return [loc, items.length, containers, labeled];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    margin: { left: 14, right: 14 },
  });

  // Page 6: Training Roster
  doc.addPage();
  addHeader(doc, "Training Roster");
  autoTable(doc, {
    startY: 28,
    head: [["Employee", "Role", "Hire Date", ...trainingCourses.map((c) => c.title.substring(0, 12))]],
    body: employees.map((emp) => {
      return [
        emp.name,
        emp.role,
        emp.hireDate,
        ...trainingCourses.map((c) => {
          const t = emp.trainings.find((tr) => tr.courseId === c.id);
          if (!t) return "N/A";
          if (t.status === "completed") return "Done";
          if (t.status === "overdue") return "OVERDUE";
          return t.status;
        }),
      ];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 6 },
    bodyStyles: { fontSize: 6 },
    columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 22 }, 2: { cellWidth: 18 } },
    margin: { left: 8, right: 8 },
  });

  // Page 7: Contractor Log
  doc.addPage();
  addHeader(doc, "Contractor Communication Log");
  y = 34;
  doc.setFontSize(10);
  doc.text("Contractor Safety Packet generation is available via ShieldSDS.", 14, y);
  y += 6;
  doc.text("Packets include: chemical hazards summary, SDS access info, emergency procedures, PPE requirements.", 14, y);
  y += 6;
  doc.text("Digital acknowledgment capture available for contractor sign-off.", 14, y);

  // Page 8: Audit Trail
  doc.addPage();
  addHeader(doc, "Audit Trail");
  autoTable(doc, {
    startY: 28,
    head: [["Timestamp", "Event"]],
    body: auditLog.slice(0, 15).map((entry) => [entry.time, entry.entry]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    columnStyles: { 0: { cellWidth: 55 } },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc);
  doc.save("ShieldSDS-Inspection-Packet.pdf");
}

// ─── 2. HazCom Program PDF ───────────────────────────────────────────────────

export async function generateHazComProgramPDF() {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();
  // Title
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 40, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Written Hazard Communication Program", w / 2, 16, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Per OSHA 29 CFR 1910.1200`, w / 2, 24, { align: "center" });
  doc.text(`${shopInfo.name} — ${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 32, { align: "center" });
  doc.setTextColor(0, 0, 0);

  let y = 50;
  const lineHeight = 5;
  const pageHeight = doc.internal.pageSize.getHeight() - 20;

  function checkPage(needed: number) {
    if (y + needed > pageHeight) {
      doc.addPage();
      y = 20;
    }
  }

  function sectionTitle(num: number, title: string) {
    checkPage(20);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(`Section ${num}: ${title}`, 14, y);
    y += 2;
    doc.setDrawColor(...NAVY);
    doc.line(14, y, w - 14, y);
    y += 6;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
  }

  function addParagraph(text: string) {
    checkPage(10);
    const lines = doc.splitTextToSize(text, w - 28);
    doc.text(lines, 14, y);
    y += lines.length * lineHeight + 2;
  }

  // Section 1
  sectionTitle(1, "Purpose and Scope");
  addParagraph(`This Written Hazard Communication Program has been established for ${shopInfo.name} in compliance with OSHA's Hazard Communication Standard, 29 CFR 1910.1200. This program applies to all employees who may be exposed to hazardous chemicals during normal work operations or in foreseeable emergencies.`);

  // Section 2
  sectionTitle(2, "Responsible Person");
  addParagraph(`Name: ${shopInfo.owner} — Title: Owner/Manager — Phone: ${shopInfo.ownerPhone} — Email: ${shopInfo.ownerEmail}`);

  // Section 3
  sectionTitle(3, "Chemical Inventory");
  addParagraph(`A complete inventory of ${sdsEntries.length} hazardous chemicals is maintained. ${sdsEntries.filter(s => s.sdsStatus === "current").length} have current SDS on file.`);
  checkPage(60);
  autoTable(doc, {
    startY: y,
    head: [["#", "Product", "Manufacturer", "Location", "Signal Word", "SDS"]],
    body: sdsEntries.map((s, i) => [i + 1, s.productName, s.manufacturer, s.storageLocation, s.signalWord, s.sdsStatus]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
    bodyStyles: { fontSize: 6 },
    margin: { left: 14, right: 14 },
  });
  y = getFinalY(doc) + 8;

  // Sections 4-8
  sectionTitle(4, "Safety Data Sheet (SDS) Access");
  addParagraph("SDS are accessible via: (1) ShieldSDS on shop tablet at Station 1, (2) QR codes on secondary container labels, (3) Offline-cached SDS on tablet, (4) Printed PDF binder in Front Office filing cabinet.");

  sectionTitle(5, "Labeling System");
  addParagraph("All containers are labeled per 29 CFR 1910.1200(f). Shipped containers retain manufacturer GHS labels. Secondary containers receive ShieldSDS-generated GHS labels with product identifier, signal word, pictograms, hazard/precautionary statements, and QR code.");

  sectionTitle(6, "Employee Training");
  addParagraph("Training is provided at initial assignment and when new chemical hazards are introduced, per 29 CFR 1910.1200(h).");
  checkPage(50);
  autoTable(doc, {
    startY: y,
    head: [["Employee", "Role", "Status", "Completed/Total"]],
    body: employees.map((emp) => {
      const stats = getEmployeeTrainingStats(emp);
      return [emp.name, emp.role, emp.status, `${stats.completed}/${stats.total}`];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
    bodyStyles: { fontSize: 7 },
    margin: { left: 14, right: 14 },
  });
  y = getFinalY(doc) + 8;

  sectionTitle(7, "Non-Routine Tasks");
  nonRoutineTasks.forEach((task) => {
    checkPage(20);
    doc.setFont("helvetica", "bold");
    doc.text(task.task, 14, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    doc.text(`Location: ${task.location} — Frequency: ${task.frequency}`, 20, y);
    y += 5;
    doc.text(`Hazards: ${task.hazards.join(", ")}`, 20, y);
    y += 5;
    doc.text(`PPE: ${task.requiredPPE.join(", ")}`, 20, y);
    y += 8;
  });

  sectionTitle(8, "Multi-Employer / Contractor Communication");
  addParagraph("When contractors work on-site, a Contractor Safety Packet is generated via ShieldSDS with relevant chemical hazards, SDS access info, emergency procedures, and PPE requirements. Digital acknowledgment is captured before work begins.");

  // Signature line
  checkPage(30);
  y += 10;
  doc.line(14, y, 90, y);
  y += 5;
  doc.setFontSize(8);
  doc.text("Signature — HazCom Program Coordinator", 14, y);
  y += 8;
  doc.line(14, y, 90, y);
  y += 5;
  doc.text("Date", 14, y);

  addFooter(doc);
  doc.save("ShieldSDS-HazCom-Program.pdf");
}

// ─── 3. Training Roster PDF ──────────────────────────────────────────────────

export async function generateTrainingRosterPDF() {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "letter" });

  addHeader(doc, "Employee Training Roster");

  autoTable(doc, {
    startY: 28,
    head: [["Employee", "Role", "Hire Date", ...trainingCourses.map((c) => c.title)]],
    body: employees.map((emp) => [
      emp.name,
      emp.role,
      emp.hireDate,
      ...trainingCourses.map((c) => {
        const t = emp.trainings.find((tr) => tr.courseId === c.id);
        if (!t) return "N/A";
        if (t.status === "completed") return `Done ${t.completedDate || ""}`;
        if (t.status === "overdue") return `OVERDUE (due ${t.dueDate || ""})`;
        if (t.status === "in-progress") return "In Progress";
        return `Due ${t.dueDate || ""}`;
      }),
    ]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 6, cellPadding: 2 },
    bodyStyles: { fontSize: 6, cellPadding: 2 },
    columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 22 }, 2: { cellWidth: 18 } },
    margin: { left: 8, right: 8 },
  });

  // Summary row
  const y = getFinalY(doc) + 8;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("Summary:", 8, y);
  doc.setFont("helvetica", "normal");
  const fullyTrained = employees.filter((e) => e.status === "current").length;
  doc.text(`${fullyTrained}/${employees.length} employees fully trained (${Math.round((fullyTrained / employees.length) * 100)}%)`, 30, y);

  addFooter(doc);
  doc.save("ShieldSDS-Training-Roster.pdf");
}

// ─── 4. Contractor Packet PDF ────────────────────────────────────────────────

export async function generateContractorPacketPDF(packet?: { company: string; contact: string; locations: string[]; startDate: string; endDate: string }) {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 35, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Contractor Safety Information Packet", w / 2, 14, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`${shopInfo.name} — ${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 22, { align: "center" });
  if (packet) {
    doc.text(`Contractor: ${packet.company} | Contact: ${packet.contact} | Dates: ${packet.startDate} to ${packet.endDate}`, w / 2, 30, { align: "center" });
  }
  doc.setTextColor(0, 0, 0);

  let y = 44;
  const lineHeight = 5;
  const pageHeight = doc.internal.pageSize.getHeight() - 20;

  function checkPage(needed: number) {
    if (y + needed > pageHeight) { doc.addPage(); y = 20; }
  }

  // Section 1: Chemical Hazards Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("1. Chemical Hazards Summary", 14, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  const locs = packet?.locations || Array.from(new Set(inventoryItems.map((i) => i.location)));
  const chemicalsInArea = inventoryItems.filter((i) => locs.includes(i.location));
  const lines = doc.splitTextToSize(`The following ${chemicalsInArea.length} chemicals are present in the work areas: ${locs.join(", ")}.`, w - 28);
  doc.text(lines, 14, y);
  y += lines.length * lineHeight + 4;

  checkPage(40);
  autoTable(doc, {
    startY: y,
    head: [["Chemical", "Location", "Signal Word", "Primary Hazards"]],
    body: chemicalsInArea.map((inv) => {
      const sds = sdsEntries.find((s) => s.id === inv.sdsId);
      return [
        inv.product,
        inv.location,
        sds?.signalWord || "—",
        sds?.pictograms.map((p) => ghsPictogramLabels[p]).join(", ") || "—",
      ];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
    bodyStyles: { fontSize: 7 },
    margin: { left: 14, right: 14 },
  });
  y = getFinalY(doc) + 10;

  // Section 2: SDS Access
  checkPage(30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("2. SDS Access", 14, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const accessMethods = [
    "QR Codes: Scan any secondary container label to view SDS on your phone",
    "Shop Tablet: ShieldSDS app on shop tablet in the front office",
    "Front Office: Ask Sarah Chen at the front desk for printed copies",
  ];
  accessMethods.forEach((m) => { doc.text(`- ${m}`, 18, y); y += 5; });
  y += 5;

  // Section 3: Emergency Procedures
  checkPage(30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("3. Emergency Procedures", 14, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Fire/EMS: ${shopInfo.emergencyContacts.fire}`, 18, y); y += 5;
  doc.text(`Poison Control: ${shopInfo.emergencyContacts.poisonControl}`, 18, y); y += 5;
  doc.text(`Responsible Person: ${shopInfo.owner} — ${shopInfo.ownerPhone}`, 18, y); y += 5;
  doc.text(`Hospital: ${shopInfo.emergencyContacts.nearestHospital.name} — ${shopInfo.emergencyContacts.nearestHospital.phone}`, 18, y); y += 10;

  // Section 4: PPE Requirements
  checkPage(20);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("4. PPE Requirements", 14, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  locs.forEach((loc) => {
    checkPage(8);
    const hasPaint = loc.includes("Paint") || loc.includes("Booth");
    doc.text(`- ${loc}: ${hasPaint ? "Safety glasses, nitrile gloves, organic vapor respirator, coveralls" : "Safety glasses, nitrile gloves minimum — check SDS"}`, 18, y);
    y += 5;
  });
  y += 5;

  // Section 5: Acknowledgment
  checkPage(40);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("5. Acknowledgment", 14, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const ackText = `I acknowledge that I have received and reviewed the chemical safety information for work at ${shopInfo.name}. I understand the hazards present, how to access SDS, and the emergency procedures.`;
  const ackLines = doc.splitTextToSize(ackText, w - 28);
  doc.text(ackLines, 14, y);
  y += ackLines.length * lineHeight + 10;
  doc.line(14, y, 100, y);
  y += 5;
  doc.text("Signature", 14, y);
  doc.line(120, y - 5, w - 14, y - 5);
  doc.text("Date", 120, y);

  addFooter(doc);
  doc.save(`ShieldSDS-Contractor-Packet${packet ? "-" + packet.company.replace(/\s+/g, "-") : ""}.pdf`);
}

// ─── 5. SDS Binder PDF ──────────────────────────────────────────────────────

export async function generateSdsBinderPDF() {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();

  // Cover / TOC
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 35, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Safety Data Sheet Binder", w / 2, 14, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`${shopInfo.name} — ${sdsEntries.length} Chemicals`, w / 2, 24, { align: "center" });
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`, w / 2, 31, { align: "center" });

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Table of Contents", 14, 48);

  autoTable(doc, {
    startY: 54,
    head: [["#", "Product Name", "Manufacturer", "Signal Word", "Page"]],
    body: sdsEntries.map((s, i) => [i + 1, s.productName, s.manufacturer, s.signalWord, i + 2]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    margin: { left: 14, right: 14 },
  });

  // One page per chemical
  sdsEntries.forEach((sds) => {
    doc.addPage();
    addHeader(doc, sds.productName);

    let y = 30;
    const pageHeight = doc.internal.pageSize.getHeight() - 20;

    function checkPage(needed: number) {
      if (y + needed > pageHeight) { doc.addPage(); addHeader(doc, sds.productName); y = 30; }
    }

    // Identification
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("1. Identification", 14, y); y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`Product: ${sds.productName}`, 18, y); y += 4;
    doc.text(`Manufacturer: ${sds.manufacturer}`, 18, y); y += 4;
    doc.text(`Code: ${sds.productCode}`, 18, y); y += 4;
    doc.text(`Address: ${sds.supplierAddress}`, 18, y); y += 4;
    doc.text(`Phone: ${sds.supplierPhone}`, 18, y); y += 6;

    // Hazard Identification
    checkPage(20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("2. Hazard Identification", 14, y); y += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Signal Word: ${sds.signalWord}`, 18, y); y += 4;
    doc.text(`Pictograms: ${sds.pictograms.map((p) => ghsPictogramLabels[p]).join(", ") || "None"}`, 18, y); y += 5;

    if (sds.hazardStatements.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.text("Hazard Statements:", 18, y); y += 4;
      doc.setFont("helvetica", "normal");
      sds.hazardStatements.forEach((h) => { checkPage(5); doc.text(`- ${h}`, 22, y); y += 4; });
      y += 2;
    }

    if (sds.precautionaryStatements.length > 0) {
      checkPage(8);
      doc.setFont("helvetica", "bold");
      doc.text("Precautionary Statements:", 18, y); y += 4;
      doc.setFont("helvetica", "normal");
      sds.precautionaryStatements.forEach((p) => { checkPage(5); doc.text(`- ${p}`, 22, y); y += 4; });
      y += 2;
    }

    // Composition
    if (sds.composition.length > 0) {
      checkPage(20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text("3. Composition", 14, y); y += 6;
      autoTable(doc, {
        startY: y,
        head: [["Ingredient", "CAS #", "Concentration"]],
        body: sds.composition.map((c) => [c.ingredient, c.casNumber, c.concentration]),
        theme: "grid",
        headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
        bodyStyles: { fontSize: 7 },
        margin: { left: 18, right: 14 },
      });
      y = getFinalY(doc) + 6;
    }

    // PPE
    checkPage(20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("8. PPE Requirements", 14, y); y += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Eyes: ${sds.ppe.eyes}`, 18, y); y += 4;
    doc.text(`Skin: ${sds.ppe.skin}`, 18, y); y += 4;
    doc.text(`Respiratory: ${sds.ppe.respiratory}`, 18, y); y += 4;
    doc.text(`Hands: ${sds.ppe.hands}`, 18, y); y += 6;

    // Physical Properties
    checkPage(18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("9. Physical Properties", 14, y); y += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Appearance: ${sds.appearance}`, 18, y); y += 4;
    doc.text(`Odor: ${sds.odor}`, 18, y); y += 4;
    doc.text(`Flash Point: ${sds.flashPoint}`, 18, y); y += 6;

    // Storage, Spill, Fire
    checkPage(18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("7. Storage", 14, y); y += 5;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    const storLines = doc.splitTextToSize(sds.storageRequirements, w - 32);
    doc.text(storLines, 18, y); y += storLines.length * 4 + 4;

    checkPage(12);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("6. Spill Procedures", 14, y); y += 5;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    const spillLines = doc.splitTextToSize(sds.spillProcedures, w - 32);
    doc.text(spillLines, 18, y); y += spillLines.length * 4 + 4;

    checkPage(12);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("5. Fire-Fighting", 14, y); y += 5;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Media: ${sds.fireFighting.extinguishingMedia}`, 18, y); y += 4;
    const hazLines = doc.splitTextToSize(`Hazards: ${sds.fireFighting.specialHazards}`, w - 32);
    doc.text(hazLines, 18, y);
  });

  addFooter(doc);
  doc.save("ShieldSDS-SDS-Binder.pdf");
}
