"use client";

import {
  sdsEntries,
  inventoryItems,
  employees,
  trainingCourses,
  auditLog,
  shopInfo,
  programVersionHistory,
  nonRoutineTasks,
  ghsPictogramLabels,
  getEmployeeTrainingStats,
  getComplianceData,
} from "./data";

// ─── Dynamic jsPDF loader ────────────────────────────────────────────────────

async function loadJsPDF() {
  const mod = await import("jspdf");
  const jsPDF = mod.default || mod.jsPDF;
  await import("jspdf-autotable");
  return jsPDF;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Doc = any;

// ─── Constants ───────────────────────────────────────────────────────────────

const NAVY: [number, number, number] = [11, 20, 38];
const WHITE: [number, number, number] = [255, 255, 255];
const GRAY: [number, number, number] = [120, 130, 145];
const AMBER: [number, number, number] = [245, 158, 11];
const RED: [number, number, number] = [239, 68, 68];
const GREEN: [number, number, number] = [34, 197, 94];

const dateStr = () =>
  new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
const dateFile = () => {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function addHeader(doc: Doc, title: string) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 22, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 15);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(shopInfo.name, w - 14, 15, { align: "right" });
  doc.setTextColor(0, 0, 0);
}

function addFooter(doc: Doc, label?: string) {
  const pageCount = doc.internal.getNumberOfPages();
  const footerLabel = label || `Generated by ShieldSDS — ${dateStr()} — ${shopInfo.name}`;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(footerLabel, 14, h - 8);
    doc.text(`Page ${i} of ${pageCount}`, w - 14, h - 8, { align: "right" });
  }
}

function autoTable(doc: Doc, opts: Record<string, unknown>) {
  doc.autoTable(opts);
}

function getFinalY(doc: Doc): number {
  return doc.lastAutoTable?.finalY || 30;
}

// ─── A. Inspection Packet PDF ────────────────────────────────────────────────

export async function generateInspectionPacket(): Promise<void> {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();
  const compliance = getComplianceData();

  // ── Page 1: Cover ──
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 280, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("ShieldSDS", w / 2, 55, { align: "center" });
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("Inspection Readiness", w / 2, 80, { align: "center" });
  doc.text("Report", w / 2, 94, { align: "center" });
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(shopInfo.name, w / 2, 115, { align: "center" });
  doc.text(`${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 124, { align: "center" });
  doc.text(shopInfo.phone, w / 2, 133, { align: "center" });
  doc.text(`Generated: ${dateStr()}`, w / 2, 148, { align: "center" });

  // Compliance score
  const scoreColor = compliance.score >= 90 ? GREEN : compliance.score >= 70 ? AMBER : RED;
  doc.setFontSize(56);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...scoreColor);
  doc.text(`${compliance.score}%`, w / 2, 190, { align: "center" });
  doc.setFontSize(14);
  doc.setTextColor(...WHITE);
  doc.text("Compliance Score", w / 2, 204, { align: "center" });

  // ── Page 2: Compliance Summary ──
  doc.addPage();
  addHeader(doc, "Compliance Summary");

  const currentSDS = sdsEntries.filter((s) => s.sdsStatus === "current").length;
  const missingSDS = sdsEntries.filter((s) => s.sdsStatus === "missing").length;
  const totalContainers = inventoryItems.reduce((sum, i) => sum + i.containers, 0);
  const labeledContainers = inventoryItems.filter((i) => i.labeled).reduce((sum, i) => sum + i.containers, 0);
  const fullyTrained = employees.filter((e) => e.status === "current").length;
  const hasProgram = programVersionHistory.length > 0;

  const obligations = [
    { name: "Written HazCom Program", status: hasProgram ? "Pass" : "Fail", detail: hasProgram ? `Version ${programVersionHistory[0].version}, last updated ${programVersionHistory[0].date}` : "No written program on file" },
    { name: "SDS Availability", status: missingSDS === 0 ? "Pass" : missingSDS <= 2 ? "Warning" : "Fail", detail: `${currentSDS}/${sdsEntries.length} current. ${missingSDS} missing.` },
    { name: "Container Labeling", status: labeledContainers === totalContainers ? "Pass" : labeledContainers / totalContainers > 0.8 ? "Warning" : "Fail", detail: `${labeledContainers}/${totalContainers} containers labeled` },
    { name: "Employee Training", status: fullyTrained === employees.length ? "Pass" : fullyTrained / employees.length > 0.7 ? "Warning" : "Fail", detail: `${fullyTrained}/${employees.length} employees fully trained` },
    { name: "Chemical Inventory", status: "Pass", detail: `${sdsEntries.length} chemicals tracked across ${new Set(inventoryItems.map((i) => i.location)).size} locations` },
    { name: "Contractor Communication", status: "Pass", detail: "Contractor packet system active" },
  ];

  autoTable(doc, {
    startY: 28,
    head: [["OSHA Obligation", "Status", "Details"]],
    body: obligations.map((o) => [o.name, o.status, o.detail]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 9 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 1: { cellWidth: 22 } },
    margin: { left: 14, right: 14 },
    didParseCell: (data: { section: string; column: { index: number }; cell: { styles: { textColor: number[] } }; row: { index: number } }) => {
      if (data.section === "body" && data.column.index === 1) {
        const val = obligations[data.row.index]?.status;
        if (val === "Pass") data.cell.styles.textColor = [...GREEN];
        else if (val === "Warning") data.cell.styles.textColor = [...AMBER];
        else if (val === "Fail") data.cell.styles.textColor = [...RED];
      }
    },
  });

  // Non-compliant items detail
  let y = getFinalY(doc) + 10;
  const nonCompliant = obligations.filter((o) => o.status !== "Pass");
  if (nonCompliant.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Items Requiring Attention:", 14, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    nonCompliant.forEach((item) => {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(item.status === "Fail" ? RED[0] : AMBER[0], item.status === "Fail" ? RED[1] : AMBER[1], item.status === "Fail" ? RED[2] : AMBER[2]);
      doc.text(`[${item.status.toUpperCase()}] ${item.name}`, 14, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);
      doc.text(item.detail, 20, y);
      y += 7;
    });
  }

  // ── Page 3: Chemical Inventory ──
  doc.addPage();
  addHeader(doc, "Chemical Inventory");
  autoTable(doc, {
    startY: 28,
    head: [["#", "Product Name", "Manufacturer", "Location", "Signal Word", "SDS Status"]],
    body: sdsEntries.map((s, i) => [
      i + 1,
      s.productName,
      s.manufacturer,
      s.storageLocation,
      s.signalWord,
      s.sdsStatus.charAt(0).toUpperCase() + s.sdsStatus.slice(1),
    ]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14 },
    didParseCell: (data: { section: string; column: { index: number }; cell: { text: string[]; styles: { textColor: number[] } } }) => {
      if (data.section === "body" && data.column.index === 5) {
        const val = data.cell.text[0];
        if (val === "Missing") data.cell.styles.textColor = [...RED];
        else if (val === "Review") data.cell.styles.textColor = [...AMBER];
      }
    },
  });

  // ── Page 4: SDS Coverage ──
  doc.addPage();
  addHeader(doc, "SDS Coverage");
  const reviewSDS = sdsEntries.filter((s) => s.sdsStatus === "review").length;
  y = 34;
  doc.setFontSize(11);
  doc.text(`Total SDS Entries: ${sdsEntries.length}`, 14, y); y += 8;
  doc.setTextColor(...GREEN);
  doc.text(`Current: ${currentSDS}`, 14, y); y += 6;
  doc.setTextColor(...AMBER);
  doc.text(`Needs Review: ${reviewSDS}`, 14, y); y += 6;
  doc.setTextColor(...RED);
  doc.text(`Missing: ${missingSDS}`, 14, y); y += 6;
  doc.setTextColor(0, 0, 0);
  doc.text(`Coverage: ${Math.round((currentSDS / sdsEntries.length) * 100)}%`, 14, y); y += 12;

  autoTable(doc, {
    startY: y,
    head: [["Product", "Manufacturer", "SDS Date", "Revision", "Status"]],
    body: sdsEntries.map((s) => [s.productName, s.manufacturer, s.sdsDate, s.sdsRevision, s.sdsStatus.charAt(0).toUpperCase() + s.sdsStatus.slice(1)]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    margin: { left: 14, right: 14 },
    didParseCell: (data: { section: string; column: { index: number }; cell: { text: string[]; styles: { textColor: number[] } } }) => {
      if (data.section === "body" && data.column.index === 4) {
        const val = data.cell.text[0];
        if (val === "Missing") data.cell.styles.textColor = [...RED];
        else if (val === "Review") data.cell.styles.textColor = [...AMBER];
      }
    },
  });

  // ── Page 5: Label Compliance ──
  doc.addPage();
  addHeader(doc, "Label Compliance");
  y = 34;
  doc.setFontSize(11);
  doc.text(`Total Containers: ${totalContainers}`, 14, y); y += 7;
  doc.text(`Labeled: ${labeledContainers}`, 14, y); y += 7;
  doc.text(`Unlabeled: ${totalContainers - labeledContainers}`, 14, y); y += 7;
  doc.text(`Compliance: ${totalContainers > 0 ? Math.round((labeledContainers / totalContainers) * 100) : 100}%`, 14, y); y += 12;

  const locations = Array.from(new Set(inventoryItems.map((i) => i.location)));
  autoTable(doc, {
    startY: y,
    head: [["Location", "Chemicals", "Containers", "Labeled", "Unlabeled"]],
    body: locations.map((loc) => {
      const items = inventoryItems.filter((i) => i.location === loc);
      const containers = items.reduce((sum, i) => sum + i.containers, 0);
      const labeled = items.filter((i) => i.labeled).reduce((sum, i) => sum + i.containers, 0);
      return [loc, items.length, containers, labeled, containers - labeled];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    margin: { left: 14, right: 14 },
  });

  // ── Page 6: Training Roster ──
  doc.addPage();
  addHeader(doc, "Training Roster");
  autoTable(doc, {
    startY: 28,
    head: [["Employee", "Role", "Hire Date", ...trainingCourses.map((c) => c.title.substring(0, 14))]],
    body: employees.map((emp) => [
      emp.name,
      emp.role,
      emp.hireDate,
      ...trainingCourses.map((c) => {
        const t = emp.trainings.find((tr) => tr.courseId === c.id);
        if (!t) return "N/A";
        if (t.status === "completed") return "Done";
        if (t.status === "overdue") return "OVERDUE";
        return t.status;
      }),
    ]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 6 },
    bodyStyles: { fontSize: 6 },
    columnStyles: { 0: { cellWidth: 26 }, 1: { cellWidth: 20 }, 2: { cellWidth: 16 } },
    margin: { left: 8, right: 8 },
  });

  // ── Page 7: Contractor Communication Log ──
  doc.addPage();
  addHeader(doc, "Contractor Communication Log");
  y = 34;
  doc.setFontSize(10);
  doc.text("Contractor Safety Packet system is active via ShieldSDS.", 14, y); y += 6;
  doc.text("Packets include: chemical hazards summary, SDS access info, emergency procedures, PPE requirements.", 14, y); y += 6;
  doc.text("Digital acknowledgment capture is available for contractor sign-off.", 14, y); y += 6;
  doc.text("All generated packets are logged in the audit trail below.", 14, y);

  // ── Page 8: Audit Trail ──
  doc.addPage();
  addHeader(doc, "Audit Trail — Last 30 Days");
  autoTable(doc, {
    startY: 28,
    head: [["Timestamp", "Event"]],
    body: auditLog.slice(0, 30).map((entry) => [entry.time, entry.entry]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    columnStyles: { 0: { cellWidth: 55 } },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc);
  doc.save(`ShieldSDS-Inspection-Packet-${dateFile()}.pdf`);
}

// ─── B. SDS Binder PDF ───────────────────────────────────────────────────────

export async function generateSDSBinder(): Promise<void> {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // Cover page
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 280, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("Safety Data Sheet Binder", w / 2, 80, { align: "center" });
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(shopInfo.name, w / 2, 100, { align: "center" });
  doc.text(`${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 110, { align: "center" });
  doc.text(`${sdsEntries.length} Chemicals`, w / 2, 125, { align: "center" });
  doc.text(`Generated: ${dateStr()}`, w / 2, 140, { align: "center" });

  // Table of contents
  doc.addPage();
  addHeader(doc, "Table of Contents");
  const sorted = [...sdsEntries].sort((a, b) => a.productName.localeCompare(b.productName));
  autoTable(doc, {
    startY: 28,
    head: [["#", "Product Name", "Manufacturer", "Signal Word", "Page"]],
    body: sorted.map((s, i) => [i + 1, s.productName, s.manufacturer, s.signalWord, i + 3]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
    bodyStyles: { fontSize: 7 },
    margin: { left: 14, right: 14 },
  });

  // One page/section per chemical
  sorted.forEach((sds) => {
    doc.addPage();
    addHeader(doc, sds.productName);
    let y = 30;

    function checkPage(needed: number) {
      if (y + needed > pageH - 20) { doc.addPage(); addHeader(doc, sds.productName); y = 30; }
    }

    function sectionHead(num: string, title: string) {
      checkPage(14);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text(`Section ${num}: ${title}`, 14, y);
      doc.setTextColor(0, 0, 0);
      y += 6;
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
    }

    function line(text: string) {
      checkPage(5);
      const lines = doc.splitTextToSize(text, w - 36);
      doc.text(lines, 18, y);
      y += lines.length * 4 + 1;
    }

    // Section 1: Identification
    sectionHead("1", "Identification");
    line(`Product: ${sds.productName}`);
    line(`Manufacturer: ${sds.manufacturer}`);
    line(`Product Code: ${sds.productCode}`);
    line(`Address: ${sds.supplierAddress}`);
    line(`Phone: ${sds.supplierPhone}`);
    y += 3;

    // Section 2: Hazard Identification
    sectionHead("2", "Hazard Identification");
    line(`Signal Word: ${sds.signalWord}`);
    line(`Pictograms: ${sds.pictograms.map((p) => ghsPictogramLabels[p]).join(", ") || "None"}`);
    if (sds.hazardStatements.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.text("Hazard Statements:", 18, y); y += 4;
      doc.setFont("helvetica", "normal");
      sds.hazardStatements.forEach((h) => { line(`  - ${h}`); });
    }
    if (sds.precautionaryStatements.length > 0) {
      checkPage(8);
      doc.setFont("helvetica", "bold");
      doc.text("Precautionary Statements:", 18, y); y += 4;
      doc.setFont("helvetica", "normal");
      sds.precautionaryStatements.forEach((p) => { line(`  - ${p}`); });
    }
    y += 3;

    // Section 3: Composition
    if (sds.composition.length > 0) {
      sectionHead("3", "Composition / Ingredients");
      checkPage(20);
      autoTable(doc, {
        startY: y,
        head: [["Ingredient", "CAS Number", "Concentration"]],
        body: sds.composition.map((c) => [c.ingredient, c.casNumber, c.concentration]),
        theme: "grid",
        headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
        bodyStyles: { fontSize: 7 },
        margin: { left: 18, right: 14 },
      });
      y = getFinalY(doc) + 5;
    }

    // Section 4: First Aid
    sectionHead("4", "First Aid Measures");
    line(`Inhalation: ${sds.firstAid.inhalation}`);
    line(`Skin Contact: ${sds.firstAid.skin}`);
    line(`Eye Contact: ${sds.firstAid.eyes}`);
    line(`Ingestion: ${sds.firstAid.ingestion}`);
    y += 3;

    // Section 5: Fire-Fighting
    sectionHead("5", "Fire-Fighting Measures");
    line(`Extinguishing Media: ${sds.fireFighting.extinguishingMedia}`);
    line(`Special Hazards: ${sds.fireFighting.specialHazards}`);
    y += 3;

    // Section 6: Accidental Release
    sectionHead("6", "Accidental Release / Spill Procedures");
    line(sds.spillProcedures);
    y += 3;

    // Section 7: Handling and Storage
    sectionHead("7", "Handling and Storage");
    line(sds.storageRequirements);
    y += 3;

    // Section 8: Exposure Controls / PPE
    sectionHead("8", "Exposure Controls / PPE");
    line(`Eyes: ${sds.ppe.eyes}`);
    line(`Skin: ${sds.ppe.skin}`);
    line(`Respiratory: ${sds.ppe.respiratory}`);
    line(`Hands: ${sds.ppe.hands}`);
    y += 3;

    // Section 9: Physical Properties
    sectionHead("9", "Physical & Chemical Properties");
    line(`Appearance: ${sds.appearance}`);
    line(`Odor: ${sds.odor}`);
    line(`Flash Point: ${sds.flashPoint}`);
    y += 3;

    // Sections 12-15
    checkPage(12);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...GRAY);
    doc.text("Sections 12-15: Not enforced by OSHA per 29 CFR 1910.1200(g)(2)", 14, y);
    doc.setTextColor(0, 0, 0);
    y += 6;

    // Section 16: Other Info
    sectionHead("16", "Other Information");
    line(`SDS Date: ${sds.sdsDate}`);
    line(`Revision: ${sds.sdsRevision}`);
    line(`Date Added to ShieldSDS: ${sds.dateAdded}`);
  });

  addFooter(doc, `Printed backup per OSHA electronic SDS backup requirement — ${dateStr()}`);
  doc.save(`SDS-Binder-${shopInfo.name.replace(/[^a-zA-Z0-9]/g, "-")}-${dateFile()}.pdf`);
}

// ─── C. HazCom Program PDF ───────────────────────────────────────────────────

export async function generateHazComProgramPDF(): Promise<void> {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  let y = 0;

  // Title block
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 42, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Written Hazard Communication Program", w / 2, 16, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Per OSHA 29 CFR 1910.1200", w / 2, 25, { align: "center" });
  doc.text(`${shopInfo.name} — ${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 33, { align: "center" });
  const ver = programVersionHistory[0];
  doc.text(`Version ${ver.version} — ${ver.date}`, w / 2, 40, { align: "center" });
  doc.setTextColor(0, 0, 0);
  y = 52;

  function checkPage(needed: number) {
    if (y + needed > pageH - 20) { doc.addPage(); y = 20; }
  }

  function sectionTitle(num: number, title: string) {
    checkPage(20);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(`Section ${num}: ${title}`, 14, y);
    y += 2;
    doc.setDrawColor(...NAVY);
    doc.line(14, y, w - 14, y);
    y += 6;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
  }

  function para(text: string) {
    checkPage(10);
    const lines = doc.splitTextToSize(text, w - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 2;
  }

  // Section 1
  sectionTitle(1, "Purpose and Scope");
  para(`This Written Hazard Communication Program has been established for ${shopInfo.name} in compliance with OSHA's Hazard Communication Standard, 29 CFR 1910.1200. This program applies to all employees who may be exposed to hazardous chemicals during normal work operations or in foreseeable emergencies.`);

  // Section 2
  sectionTitle(2, "Responsible Person");
  para(`Name: ${shopInfo.owner}\nTitle: Owner/Manager\nPhone: ${shopInfo.ownerPhone}\nEmail: ${shopInfo.ownerEmail}`);
  para("The responsible person ensures the program is implemented, maintained, and that all employees are trained.");

  // Section 3
  sectionTitle(3, "Chemical Inventory");
  para(`A complete inventory of ${sdsEntries.length} hazardous chemicals is maintained. ${sdsEntries.filter((s) => s.sdsStatus === "current").length} have current SDS on file.`);
  checkPage(60);
  autoTable(doc, {
    startY: y,
    head: [["#", "Product", "Manufacturer", "Location", "Signal Word", "SDS"]],
    body: sdsEntries.map((s, i) => [i + 1, s.productName, s.manufacturer, s.storageLocation, s.signalWord, s.sdsStatus]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
    bodyStyles: { fontSize: 6 },
    margin: { left: 14, right: 14 },
  });
  y = getFinalY(doc) + 8;

  // Section 4
  sectionTitle(4, "Safety Data Sheet (SDS) Access");
  para("SDS are accessible to all employees via the following methods:");
  para("1. ShieldSDS digital system on shop tablet at Station 1 — no login required for viewing");
  para("2. QR codes on all secondary container labels — scan to view SDS on any smartphone");
  para("3. Offline-cached SDS on the shop tablet for use when internet is unavailable");
  para("4. Printed PDF binder maintained in the Front Office filing cabinet as backup");

  // Section 5
  sectionTitle(5, "Labeling System");
  para("All containers are labeled per 29 CFR 1910.1200(f). Shipped containers retain the manufacturer's original GHS label. Secondary containers receive ShieldSDS-generated GHS labels including: product identifier, signal word, hazard pictograms, hazard statements, precautionary statements, and QR code linking to the full SDS.");

  // Section 6
  sectionTitle(6, "Employee Training");
  para("Chemical hazard training is provided at initial assignment and whenever a new chemical hazard type is introduced to the workplace, per 29 CFR 1910.1200(h). Training covers: the HazCom standard requirements, location and availability of the written program, how to read SDS, how to read labels, hazards in the work area, and protective measures.");
  checkPage(50);
  autoTable(doc, {
    startY: y,
    head: [["Employee", "Role", "Status", "Courses Completed"]],
    body: employees.map((emp) => {
      const stats = getEmployeeTrainingStats(emp);
      return [emp.name, emp.role, emp.status, `${stats.completed}/${stats.total}`];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
    bodyStyles: { fontSize: 7 },
    margin: { left: 14, right: 14 },
  });
  y = getFinalY(doc) + 8;

  // Section 7
  sectionTitle(7, "Non-Routine Tasks");
  para("The following non-routine tasks involve potential exposure to hazardous chemicals:");
  nonRoutineTasks.forEach((task) => {
    checkPage(20);
    doc.setFont("helvetica", "bold");
    doc.text(task.task, 14, y); y += 5;
    doc.setFont("helvetica", "normal");
    doc.text(`Location: ${task.location} — Frequency: ${task.frequency}`, 20, y); y += 5;
    doc.text(`Hazards: ${task.hazards.join(", ")}`, 20, y); y += 5;
    doc.text(`PPE: ${task.requiredPPE.join(", ")}`, 20, y); y += 8;
  });

  // Section 8
  sectionTitle(8, "Multi-Employer / Contractor Communication");
  para("When contractors or outside workers are present on-site and may be exposed to hazardous chemicals, a Contractor Safety Packet is generated via ShieldSDS. This packet includes: chemical hazards in their work area, SDS access instructions, emergency procedures, PPE requirements, and labeling system information. Digital acknowledgment is captured before work begins.");

  // Section 9
  sectionTitle(9, "Emergency Procedures");
  para(`Fire/EMS: ${shopInfo.emergencyContacts.fire}`);
  para(`Poison Control: ${shopInfo.emergencyContacts.poisonControl}`);
  para(`Nearest Hospital: ${shopInfo.emergencyContacts.nearestHospital.name} — ${shopInfo.emergencyContacts.nearestHospital.phone} (${shopInfo.emergencyContacts.nearestHospital.distance})`);
  para(`Responsible Person: ${shopInfo.owner} — ${shopInfo.ownerPhone}`);

  // Section 10
  sectionTitle(10, "Program Review");
  para("This program is reviewed and updated whenever new chemicals are introduced, processes change, or at least annually. ShieldSDS automatically updates the chemical inventory and training records. Version history is maintained.");

  // Signature lines
  checkPage(35);
  y += 10;
  doc.line(14, y, 90, y);
  y += 5;
  doc.setFontSize(8);
  doc.text("Signature — HazCom Program Coordinator", 14, y);
  y += 10;
  doc.line(14, y, 90, y);
  y += 5;
  doc.text("Date", 14, y);

  addFooter(doc);
  doc.save(`HazCom-Program-v${ver.version}-${dateFile()}.pdf`);
}

// ─── D. Training Roster PDF ──────────────────────────────────────────────────

export async function generateTrainingRosterPDF(): Promise<void> {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "letter" });

  addHeader(doc, `Employee Training Roster — ${shopInfo.name}`);

  autoTable(doc, {
    startY: 28,
    head: [["Employee", "Role", "Hire Date", ...trainingCourses.map((c) => c.title)]],
    body: employees.map((emp) => [
      emp.name,
      emp.role,
      emp.hireDate,
      ...trainingCourses.map((c) => {
        const t = emp.trainings.find((tr) => tr.courseId === c.id);
        if (!t) return "N/A";
        if (t.status === "completed") return `Done ${t.completedDate || ""}`;
        if (t.status === "overdue") return `OVERDUE (due ${t.dueDate || ""})`;
        if (t.status === "in-progress") return "In Progress";
        return `Due ${t.dueDate || ""}`;
      }),
    ]),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 6, cellPadding: 2 },
    bodyStyles: { fontSize: 6, cellPadding: 2 },
    columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 22 }, 2: { cellWidth: 18 } },
    margin: { left: 8, right: 8 },
  });

  // Summary stats
  const y = getFinalY(doc) + 8;
  const fullyTrained = employees.filter((e) => e.status === "current").length;
  const overdueCount = employees.flatMap((e) => e.trainings).filter((t) => t.status === "overdue").length;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Summary:", 8, y);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Total Employees: ${employees.length} | Fully Trained: ${fullyTrained} (${Math.round((fullyTrained / employees.length) * 100)}%) | Overdue Trainings: ${overdueCount}`,
    30,
    y
  );

  addFooter(doc);
  doc.save(`Training-Roster-${dateFile()}.pdf`);
}

// ─── E. Contractor Packet PDF ────────────────────────────────────────────────

export async function generateContractorPacketPDF(packet?: {
  company: string;
  contact: string;
  locations: string[];
  startDate: string;
  endDate: string;
}): Promise<void> {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const w = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  let y = 0;

  // Header block
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, w, 38, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Contractor Safety Information Packet", w / 2, 14, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`${shopInfo.name} — ${shopInfo.address}, ${shopInfo.city}, ${shopInfo.state} ${shopInfo.zip}`, w / 2, 23, { align: "center" });
  if (packet) {
    doc.text(`Contractor: ${packet.company} | Contact: ${packet.contact}`, w / 2, 30, { align: "center" });
    doc.text(`Dates: ${packet.startDate} to ${packet.endDate}`, w / 2, 36, { align: "center" });
  }
  doc.setTextColor(0, 0, 0);
  y = 46;

  function checkPage(needed: number) {
    if (y + needed > pageH - 20) { doc.addPage(); y = 20; }
  }

  // Section 1: Chemical Hazards Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("1. Chemical Hazards Summary", 14, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  const locs = packet?.locations || Array.from(new Set(inventoryItems.map((i) => i.location)));
  const chemicalsInArea = inventoryItems.filter((i) => locs.includes(i.location));
  const intro = doc.splitTextToSize(`The following ${chemicalsInArea.length} chemicals are present in the work areas: ${locs.join(", ")}.`, w - 28);
  doc.text(intro, 14, y); y += intro.length * 5 + 4;

  checkPage(40);
  autoTable(doc, {
    startY: y,
    head: [["Chemical", "Location", "Signal Word", "Pictograms", "Primary Hazards"]],
    body: chemicalsInArea.map((inv) => {
      const sds = sdsEntries.find((s) => s.id === inv.sdsId);
      return [
        inv.product,
        inv.location,
        sds?.signalWord || "—",
        sds?.pictograms.map((p) => ghsPictogramLabels[p]).join(", ") || "—",
        sds?.hazardStatements.slice(0, 2).join("; ") || "—",
      ];
    }),
    theme: "grid",
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 7 },
    bodyStyles: { fontSize: 6 },
    margin: { left: 14, right: 14 },
  });
  y = getFinalY(doc) + 10;

  // Section 2: Labeling System
  checkPage(25);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("2. Labeling System", 14, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const labelText = doc.splitTextToSize("All containers at this facility use GHS-compliant labels. Secondary containers have labels with: product identifier, signal word, hazard pictograms, hazard/precautionary statements, and a QR code linking to the full SDS. Original manufacturer labels are maintained on all shipped containers.", w - 28);
  doc.text(labelText, 14, y); y += labelText.length * 5 + 6;

  // Section 3: SDS Access
  checkPage(25);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("3. SDS Access", 14, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const accessMethods = [
    "QR Codes: Scan any secondary container label to view SDS on your phone",
    "Shop Tablet: ShieldSDS app on shop tablet at Station 1 — no login required",
    "Front Office: Ask at the front desk for printed copies",
    `Online: SDS accessible at shieldsds.vercel.app`,
  ];
  accessMethods.forEach((m) => { doc.text(`  - ${m}`, 18, y); y += 5; });
  y += 5;

  // Section 4: Emergency Procedures
  checkPage(30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("4. Emergency Procedures", 14, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Fire/EMS: ${shopInfo.emergencyContacts.fire}`, 18, y); y += 5;
  doc.text(`Poison Control: ${shopInfo.emergencyContacts.poisonControl}`, 18, y); y += 5;
  doc.text(`Responsible Person: ${shopInfo.owner} — ${shopInfo.ownerPhone}`, 18, y); y += 5;
  doc.text(`Hospital: ${shopInfo.emergencyContacts.nearestHospital.name} — ${shopInfo.emergencyContacts.nearestHospital.phone} (${shopInfo.emergencyContacts.nearestHospital.distance})`, 18, y); y += 10;

  // Section 5: PPE Requirements
  checkPage(25);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("5. PPE Requirements", 14, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  locs.forEach((loc) => {
    checkPage(8);
    const hasPaint = loc.includes("Paint") || loc.includes("Booth");
    doc.text(`  - ${loc}: ${hasPaint ? "Safety glasses, nitrile gloves, organic vapor respirator, coveralls" : "Safety glasses, nitrile gloves minimum — check SDS for specific requirements"}`, 18, y);
    y += 5;
  });
  y += 8;

  // Section 6: Acknowledgment
  checkPage(50);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("6. Acknowledgment", 14, y); y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const ackText = `I acknowledge that I have received and reviewed the chemical safety information for work at ${shopInfo.name}. I understand the hazards present in my work area(s), how to access Safety Data Sheets, the labeling system used at this facility, and the emergency procedures. I agree to follow all safety requirements and use the required PPE.`;
  const ackLines = doc.splitTextToSize(ackText, w - 28);
  doc.text(ackLines, 14, y); y += ackLines.length * 5 + 12;

  // Signature block
  doc.line(14, y, 100, y);
  y += 5;
  doc.text("Contractor Signature", 14, y);
  doc.line(120, y - 5, w - 14, y - 5);
  doc.text("Date", 120, y);
  y += 12;
  doc.line(14, y, 100, y);
  y += 5;
  doc.text("Printed Name", 14, y);
  doc.line(120, y - 5, w - 14, y - 5);
  doc.text("Company", 120, y);

  addFooter(doc);
  const companySlug = packet ? packet.company.replace(/[^a-zA-Z0-9]/g, "-") : "General";
  doc.save(`Contractor-Packet-${companySlug}-${dateFile()}.pdf`);
}

// ─── F. Label PDF ────────────────────────────────────────────────────────────

export async function generateLabelPDF(
  chemicalId: string,
  size: "4x3" | "2x1.5" | "1x1" = "4x3"
): Promise<void> {
  const jsPDF = await loadJsPDF();
  const sds = sdsEntries.find((s) => s.id === chemicalId);
  if (!sds) throw new Error(`Chemical ${chemicalId} not found`);

  if (size === "4x3") {
    // One label per page, 4" x 3"
    const doc = new jsPDF({ orientation: "landscape", unit: "in", format: [3, 4] });
    renderLabel(doc, sds, 0.15, 0.15, 3.7, 2.7);
    doc.save(`Label-${sds.productName.replace(/[^a-zA-Z0-9]/g, "-")}-4x3.pdf`);
  } else if (size === "2x1.5") {
    // Tiled: 4 per letter page
    const doc = new jsPDF({ orientation: "portrait", unit: "in", format: "letter" });
    const positions = [
      { x: 0.5, y: 0.5 },
      { x: 4.5, y: 0.5 },
      { x: 0.5, y: 4.25 },
      { x: 4.5, y: 4.25 },
    ];
    positions.forEach((pos) => {
      renderMiniLabel(doc, sds, pos.x, pos.y, 3.5, 3);
    });
    doc.save(`Label-${sds.productName.replace(/[^a-zA-Z0-9]/g, "-")}-2x1.5.pdf`);
  } else {
    // 1x1 QR-style: 20 per page (4 cols x 5 rows)
    const doc = new jsPDF({ orientation: "portrait", unit: "in", format: "letter" });
    for (let row = 0; row < 5; row++) {
      for (let col = 0; col < 4; col++) {
        const x = 0.5 + col * 2;
        const y = 0.5 + row * 2;
        renderQRLabel(doc, sds, x, y);
      }
    }
    doc.save(`Label-${sds.productName.replace(/[^a-zA-Z0-9]/g, "-")}-1x1.pdf`);
  }
}

function renderLabel(doc: Doc, sds: typeof sdsEntries[0], x: number, y: number, w: number, h: number) {
  // Border
  doc.setDrawColor(150);
  doc.setLineWidth(0.01);
  doc.rect(x, y, w, h);

  // Crop marks
  const cm = 0.1;
  doc.setDrawColor(180);
  doc.setLineWidth(0.005);
  // corners
  [
    [x, y - cm, x, y], [x - cm, y, x, y],
    [x + w, y - cm, x + w, y], [x + w + cm, y, x + w, y],
    [x, y + h, x, y + h + cm], [x - cm, y + h, x, y + h],
    [x + w, y + h, x + w, y + h + cm], [x + w + cm, y + h, x + w, y + h],
  ].forEach(([x1, y1, x2, y2]) => doc.line(x1, y1, x2, y2));

  let cy = y + 0.2;

  // Product name
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const nameLines = doc.splitTextToSize(sds.productName, w - 0.3);
  doc.text(nameLines, x + 0.15, cy);
  cy += nameLines.length * 0.22;

  // Signal word
  cy += 0.05;
  if (sds.signalWord !== "None") {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    if (sds.signalWord === "Danger") doc.setTextColor(220, 38, 38);
    else doc.setTextColor(245, 158, 11);
    doc.text(sds.signalWord.toUpperCase(), x + 0.15, cy);
    cy += 0.28;
  }

  // Pictogram names in diamonds
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const picLabels = sds.pictograms.map((p) => ghsPictogramLabels[p]);
  if (picLabels.length > 0) {
    // Draw diamond outlines with text
    let px = x + 0.15;
    picLabels.forEach((label) => {
      const tw = doc.getTextWidth(label) + 0.15;
      doc.setDrawColor(220, 38, 38);
      doc.setLineWidth(0.01);
      // Diamond shape
      const cx = px + tw / 2;
      const dh = 0.18;
      doc.line(cx, cy - dh, cx + tw / 2 + 0.04, cy);
      doc.line(cx + tw / 2 + 0.04, cy, cx, cy + dh);
      doc.line(cx, cy + dh, cx - tw / 2 - 0.04, cy);
      doc.line(cx - tw / 2 - 0.04, cy, cx, cy - dh);
      doc.setTextColor(220, 38, 38);
      doc.text(label, cx, cy + 0.03, { align: "center" });
      px += tw + 0.12;
      if (px > x + w - 0.5) { px = x + 0.15; cy += 0.42; }
    });
    cy += 0.35;
  }

  // Hazard statements
  doc.setFontSize(6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  sds.hazardStatements.slice(0, 4).forEach((stmt) => {
    if (cy > y + h - 0.5) return;
    const hLines = doc.splitTextToSize(stmt, w - 0.3);
    doc.text(hLines, x + 0.15, cy);
    cy += hLines.length * 0.12 + 0.02;
  });

  // Precautionary statements
  cy += 0.05;
  sds.precautionaryStatements.slice(0, 3).forEach((stmt) => {
    if (cy > y + h - 0.35) return;
    const pLines = doc.splitTextToSize(stmt, w - 0.3);
    doc.text(pLines, x + 0.15, cy);
    cy += pLines.length * 0.12 + 0.02;
  });

  // Manufacturer at bottom
  doc.setFontSize(5);
  doc.setTextColor(100, 100, 100);
  doc.text(sds.manufacturer, x + 0.15, y + h - 0.2);
  doc.text("Scan for SDS [QR]", x + w - 0.15, y + h - 0.2, { align: "right" });
}

function renderMiniLabel(doc: Doc, sds: typeof sdsEntries[0], x: number, y: number, w: number, h: number) {
  doc.setDrawColor(180);
  doc.setLineWidth(0.005);
  doc.setLineDashPattern([0.05, 0.05], 0);
  doc.rect(x, y, w, h);
  doc.setLineDashPattern([], 0);

  let cy = y + 0.15;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const nameLines = doc.splitTextToSize(sds.productName, w - 0.2);
  doc.text(nameLines, x + 0.1, cy);
  cy += nameLines.length * 0.16;

  if (sds.signalWord !== "None") {
    doc.setFontSize(10);
    if (sds.signalWord === "Danger") doc.setTextColor(220, 38, 38);
    else doc.setTextColor(245, 158, 11);
    doc.text(sds.signalWord.toUpperCase(), x + 0.1, cy);
    cy += 0.2;
  }

  doc.setFontSize(6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  const pics = sds.pictograms.map((p) => ghsPictogramLabels[p]).join(", ");
  if (pics) { doc.text(pics, x + 0.1, cy); cy += 0.14; }

  sds.hazardStatements.slice(0, 3).forEach((stmt) => {
    if (cy > y + h - 0.25) return;
    const hLines = doc.splitTextToSize(stmt, w - 0.2);
    doc.text(hLines, x + 0.1, cy);
    cy += hLines.length * 0.1 + 0.02;
  });

  doc.setFontSize(4.5);
  doc.setTextColor(100, 100, 100);
  doc.text(sds.manufacturer, x + 0.1, y + h - 0.08);
}

function renderQRLabel(doc: Doc, sds: typeof sdsEntries[0], x: number, y: number) {
  const size = 1.5;
  doc.setDrawColor(180);
  doc.setLineWidth(0.005);
  doc.rect(x, y, size, size);

  doc.setFontSize(6);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const nameLines = doc.splitTextToSize(sds.productName, size - 0.15);
  doc.text(nameLines.slice(0, 2), x + 0.07, y + 0.15);

  const sigY = y + 0.15 + Math.min(nameLines.length, 2) * 0.1 + 0.05;
  if (sds.signalWord !== "None") {
    doc.setFontSize(7);
    if (sds.signalWord === "Danger") doc.setTextColor(220, 38, 38);
    else doc.setTextColor(245, 158, 11);
    doc.text(sds.signalWord, x + 0.07, sigY);
  }

  // QR placeholder
  doc.setFillColor(230, 230, 230);
  doc.rect(x + size - 0.5, y + size - 0.5, 0.4, 0.4, "F");
  doc.setFontSize(4);
  doc.setTextColor(100, 100, 100);
  doc.text("QR", x + size - 0.3, y + size - 0.26, { align: "center" });
  doc.text("Scan", x + size - 0.3, y + size - 0.18, { align: "center" });
}

// ─── Batch Label Export ──────────────────────────────────────────────────────

export async function generateAllLabelsPDF(): Promise<void> {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ orientation: "landscape", unit: "in", format: [3, 4] });

  sdsEntries.forEach((sds, i) => {
    if (i > 0) doc.addPage([3, 4]);
    renderLabel(doc, sds, 0.15, 0.15, 3.7, 2.7);
  });

  doc.save(`ShieldSDS-All-Labels-${dateFile()}.pdf`);
}
