"use client";

import { useState, useMemo, useEffect, useCallback } from "react";
import Link from "next/link";
import DashboardLayout from "@/components/DashboardLayout";
import HelpCard from "@/components/HelpCard";
import { getChemicals, getEmployees, initializeStore } from "@/lib/chemicals";
import type { Chemical, Employee } from "@/lib/types";
import {
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Download,
  Clock,
  ShieldCheck,
  ChevronDown,
  ChevronRight,
  FileText,
  Tags,
  GraduationCap,
  FlaskConical,
  BookOpen,
  Link2,
  X,
  ArrowRight,
  Copy,
  MapPin,
  Send,
} from "lucide-react";

// ─── Shop Info (static config) ──────────────────────────────────────────────

const shopInfo = {
  name: "Mike's Auto Body",
  owner: "Mike Rodriguez",
  address: "1847 Pacific Coast Hwy",
  city: "Long Beach",
  state: "CA",
  zip: "90806",
  phone: "(562) 555-0147",
};

// ─── Audit category helpers ─────────────────────────────────────────────────

function getAuditCategory(entry: string): { icon: typeof FileText; color: string } {
  if (entry.includes("SDS")) return { icon: FileText, color: "text-blue-400" };
  if (entry.includes("Label") || entry.includes("label")) return { icon: Tags, color: "text-purple-400" };
  if (entry.includes("Training") || entry.includes("training")) return { icon: GraduationCap, color: "text-amber-400" };
  if (entry.includes("Program") || entry.includes("program")) return { icon: BookOpen, color: "text-emerald-400" };
  return { icon: FlaskConical, color: "text-cyan-400" };
}

// ─── Toast ────────────────────────────────────────────────────────────────────

function Toast({ message, onClose }: { message: string; onClose: () => void }) {
  return (
    <div className="fixed bottom-6 right-6 z-[60] bg-navy-800 border border-navy-600 rounded-xl px-5 py-3 flex items-center gap-3 shadow-2xl">
      <CheckCircle2 className="h-5 w-5 text-status-green flex-shrink-0" />
      <span className="text-sm text-white">{message}</span>
      <button onClick={onClose} className="text-gray-400 hover:text-white ml-2"><X className="h-4 w-4" /></button>
    </div>
  );
}

// ─── Share Modal ──────────────────────────────────────────────────────────────

function ShareModal({ onClose, onToast }: { onClose: () => void; onToast: (msg: string) => void }) {
  const [copied, setCopied] = useState(false);
  const [expiry, setExpiry] = useState("7d");
  const [accessMode, setAccessMode] = useState<"anyone" | "email">("anyone");
  const [restrictEmail, setRestrictEmail] = useState("");
  const shareId = "mikes-auto-body-2026-02-24";
  const mockUrl = `https://app.shieldsds.com/share/${shareId}`;
  const localUrl = `/share/${shareId}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(mockUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendEmail = () => {
    const subject = encodeURIComponent(`${shopInfo.name} — HazCom Compliance Report`);
    const body = encodeURIComponent(`Here is a read-only link to our HazCom compliance report:\n\n${mockUrl}\n\nThis link expires in ${expiry === "24h" ? "24 hours" : expiry === "7d" ? "7 days" : expiry === "30d" ? "30 days" : "never"}.\n\nGenerated by ShieldSDS`);
    const to = accessMode === "email" && restrictEmail ? restrictEmail : "";
    window.open(`mailto:${to}?subject=${subject}&body=${body}`, "_blank");
    onToast("Email client opened with share link");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-navy-900 border border-navy-700 rounded-2xl w-full max-w-md mx-4 shadow-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-navy-700">
          <h2 className="font-display font-bold text-lg text-white">Share Read-Only Link</h2>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-navy-800 text-gray-400 hover:text-white"><X className="h-5 w-5" /></button>
        </div>
        <div className="p-6 space-y-4">
          <div>
            <label className="text-xs text-gray-400 uppercase tracking-wider font-semibold block mb-2">Shareable URL</label>
            <div className="flex items-center gap-2">
              <input type="text" readOnly value={mockUrl} className="flex-1 bg-navy-800 border border-navy-700 rounded-lg px-3 py-2 text-xs text-white font-mono" />
              <button onClick={handleCopy} className="flex items-center gap-1 bg-amber-500 hover:bg-amber-400 text-navy-950 font-semibold text-xs px-3 py-2 rounded-lg transition-colors">
                {copied ? <CheckCircle2 className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                {copied ? "Copied" : "Copy"}
              </button>
            </div>
            <a href={localUrl} target="_blank" rel="noopener noreferrer" className="text-[10px] text-amber-400 hover:text-amber-300 mt-1 inline-block">
              Preview the shared report &rarr;
            </a>
          </div>

          <div>
            <label className="text-xs text-gray-400 uppercase tracking-wider font-semibold block mb-2">Link Expiration</label>
            <div className="flex gap-2">
              {[
                { label: "24 hours", value: "24h" },
                { label: "7 days", value: "7d" },
                { label: "30 days", value: "30d" },
                { label: "Never", value: "never" },
              ].map((opt) => (
                <button
                  key={opt.value}
                  onClick={() => setExpiry(opt.value)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                    expiry === opt.value
                      ? "bg-amber-500 text-navy-950"
                      : "bg-navy-800 text-gray-400 hover:text-white border border-navy-700"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="text-xs text-gray-400 uppercase tracking-wider font-semibold block mb-2">Access</label>
            <div className="flex gap-2">
              <button
                onClick={() => setAccessMode("anyone")}
                className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                  accessMode === "anyone" ? "bg-amber-500 text-navy-950" : "bg-navy-800 text-gray-400 hover:text-white border border-navy-700"
                }`}
              >
                Anyone with link
              </button>
              <button
                onClick={() => setAccessMode("email")}
                className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                  accessMode === "email" ? "bg-amber-500 text-navy-950" : "bg-navy-800 text-gray-400 hover:text-white border border-navy-700"
                }`}
              >
                Email-restricted
              </button>
            </div>
            {accessMode === "email" && (
              <input
                type="email"
                value={restrictEmail}
                onChange={(e) => setRestrictEmail(e.target.value)}
                placeholder="recipient@example.com"
                className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg px-3 py-2 text-xs text-white placeholder-gray-500 focus:outline-none focus:border-amber-500/50"
              />
            )}
          </div>

          <button
            onClick={handleSendEmail}
            className="w-full flex items-center justify-center gap-2 bg-navy-800 border border-navy-700 hover:border-navy-600 text-gray-300 text-sm py-2.5 rounded-lg transition-colors"
          >
            <Send className="h-4 w-4" />
            Send via Email
          </button>

          <p className="text-xs text-gray-500">
            This link gives read-only access to the compliance report summary. No full SDS content or employee details are shared.
          </p>
        </div>
      </div>
    </div>
  );
}

// ─── Expandable Checklist Item ────────────────────────────────────────────────

interface ChecklistItem {
  id: string;
  item: string;
  pass: boolean;
  warn: boolean;
  score: number;
  maxScore: number;
  detail: string;
  subItems: { label: string; ok: boolean; link?: string; fixDescription?: string; fixAction?: string }[];
}

function ChecklistCard({ item }: { item: ChecklistItem }) {
  const [expanded, setExpanded] = useState(!item.pass);

  const StatusIcon = item.pass
    ? CheckCircle2
    : item.warn
    ? AlertTriangle
    : XCircle;
  const statusColor = item.pass
    ? "text-status-green"
    : item.warn
    ? "text-status-amber"
    : "text-status-red";
  const borderColor = item.pass
    ? "border-navy-700/50"
    : item.warn
    ? "border-status-amber/30"
    : "border-status-red/30";
  const badgeClass = item.pass
    ? "bg-status-green/15 text-status-green"
    : item.warn
    ? "bg-status-amber/15 text-status-amber"
    : "bg-status-red/15 text-status-red";
  const badgeText = item.pass ? "Pass" : item.warn ? "Warning" : "Fail";

  return (
    <div className={`bg-navy-900 border rounded-xl transition-colors ${borderColor}`}>
      <button
        className="w-full flex items-center justify-between p-5 text-left"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-3 flex-1 min-w-0">
          <StatusIcon className={`h-5 w-5 ${statusColor} flex-shrink-0`} />
          <div className="flex-1 min-w-0">
            <h3 className="text-sm font-medium text-white">{item.item}</h3>
            <p className="text-xs text-gray-400 mt-0.5">{item.detail}</p>
          </div>
        </div>
        <div className="flex items-center gap-3 flex-shrink-0 ml-4">
          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${badgeClass}`}>
            {badgeText}
          </span>
          {expanded ? <ChevronDown className="h-4 w-4 text-gray-400" /> : <ChevronRight className="h-4 w-4 text-gray-400" />}
        </div>
      </button>
      {expanded && item.subItems.length > 0 && (
        <div className="px-5 pb-5 pt-0">
          <div className="border-t border-navy-700/30 pt-3 space-y-2">
            {item.subItems.map((sub, i) => (
              <div key={i} className="text-xs">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {sub.ok ? (
                      <CheckCircle2 className="h-3.5 w-3.5 text-status-green" />
                    ) : (
                      <XCircle className="h-3.5 w-3.5 text-status-red" />
                    )}
                    <span className={sub.ok ? "text-gray-400" : "text-white"}>{sub.label}</span>
                  </div>
                  {sub.link && !sub.ok && (
                    <Link href={sub.link} className="flex items-center gap-1 text-amber-400 hover:text-amber-300 transition-colors whitespace-nowrap ml-2">
                      {sub.fixAction || "Fix"} <ArrowRight className="h-3 w-3" />
                    </Link>
                  )}
                </div>
                {sub.fixDescription && !sub.ok && (
                  <p className="text-gray-500 mt-0.5 pl-[22px]">{sub.fixDescription}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Generate audit log entries from live data ──────────────────────────────

interface AuditEntry {
  time: string;
  entry: string;
}

function generateAuditLog(chemicals: Chemical[], employees: Employee[]): AuditEntry[] {
  const entries: AuditEntry[] = [];

  chemicals.forEach((c) => {
    if (c.added_date) {
      entries.push({
        time: c.added_date,
        entry: `Chemical added: ${c.product_name} (${c.added_by})`,
      });
    }
    if (c.label_printed_date) {
      entries.push({
        time: c.label_printed_date,
        entry: `Label printed: ${c.product_name} — ${c.container_count} ${c.container_type}`,
      });
    }
    if (c.sds_uploaded && c.sds_date) {
      entries.push({
        time: c.sds_date,
        entry: `SDS uploaded: ${c.product_name} (${c.manufacturer})`,
      });
    }
    if (c.sds_status === "missing") {
      entries.push({
        time: c.last_updated,
        entry: `Missing SDS flagged: ${c.product_name} — request from ${c.manufacturer}`,
      });
    }
    if (c.sds_status === "expired") {
      entries.push({
        time: c.last_updated,
        entry: `SDS expired: ${c.product_name} — needs updated version`,
      });
    }
  });

  employees.forEach((emp) => {
    if (emp.last_training) {
      entries.push({
        time: emp.last_training,
        entry: `Training completed: ${emp.name} — ${emp.role}`,
      });
    }
    if (emp.status === "overdue") {
      entries.push({
        time: emp.last_training || new Date().toISOString().split("T")[0],
        entry: `Training overdue: ${emp.name} — ${emp.pending_modules.join(", ")}`,
      });
    }
    if (emp.status === "pending") {
      entries.push({
        time: new Date().toISOString().split("T")[0],
        entry: `New hire pending training: ${emp.name} — ${emp.pending_modules.length} modules`,
      });
    }
  });

  entries.sort((a, b) => b.time.localeCompare(a.time));
  return entries;
}

// ─── Main Page ───────────────────────────────────────────────────────────────

export default function InspectionPage() {
  const [chemicals, setChemicals] = useState<Chemical[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [toast, setToast] = useState<string | null>(null);
  const [showShare, setShowShare] = useState(false);

  useEffect(() => {
    initializeStore();
    setChemicals(getChemicals());
    setEmployees(getEmployees());
  }, []);

  const showToast = useCallback((msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  }, []);

  // ── Dynamic compliance calculations ──────────────────────────────────────

  const totalSDS = chemicals.length;
  const currentSDS = chemicals.filter((c) => c.sds_status === "current").length;
  const missingSdsChems = useMemo(() => chemicals.filter((c) => c.sds_status === "missing"), [chemicals]);
  const expiredSdsChems = useMemo(() => chemicals.filter((c) => c.sds_status === "expired"), [chemicals]);

  const totalContainers = chemicals.reduce((sum, c) => sum + c.container_count, 0);
  const labeledContainers = chemicals.filter((c) => c.labeled).reduce((sum, c) => sum + c.container_count, 0);
  const unlabeledChems = useMemo(() => chemicals.filter((c) => !c.labeled), [chemicals]);
  const labelPct = totalContainers > 0 ? Math.round((labeledContainers / totalContainers) * 100) : 100;

  const totalEmployees = employees.length;
  const fullyTrained = employees.filter((e) => e.status === "current").length;
  const overdueEmployees = useMemo(() => employees.filter((e) => e.status === "overdue"), [employees]);
  const pendingEmployees = useMemo(() => employees.filter((e) => e.status === "pending"), [employees]);
  const trainingPct = totalEmployees > 0 ? Math.round((fullyTrained / totalEmployees) * 100) : 100;

  const sdsPct = totalSDS > 0 ? Math.round((currentSDS / totalSDS) * 100) : 100;

  // ── Weighted score calculation ──────────────────────────────────────────

  const weights = { sds: 25, labels: 25, training: 25, program: 15, multiEmployer: 10 };

  const sdsScore = sdsPct === 100 ? 1 : sdsPct >= 90 ? 0.5 : 0;
  const labelScore = labelPct === 100 ? 1 : labelPct >= 80 ? 0.5 : 0;
  const trainingScore = trainingPct === 100 ? 1 : trainingPct >= 80 ? 0.5 : 0;
  const programScore = 1;
  const multiScore = 1;

  const score = Math.round(
    sdsScore * weights.sds +
    labelScore * weights.labels +
    trainingScore * weights.training +
    programScore * weights.program +
    multiScore * weights.multiEmployer
  );

  const circumference = 2 * Math.PI * 52;
  const failCount = [sdsScore, labelScore, trainingScore, programScore, multiScore].filter((s) => s < 1).length;
  const readinessLabel = score === 100 ? "Fully Ready" : score >= 80 ? "Mostly Ready" : "Needs Work";
  const readinessColor = score === 100 ? "#34C759" : score >= 80 ? "#F5A623" : "#FF3B30";

  // ── Build checklist items ───────────────────────────────────────────────

  const checklist: ChecklistItem[] = useMemo(() => [
    {
      id: "1",
      item: "Written HazCom Program",
      pass: true,
      warn: false,
      score: weights.program,
      maxScore: weights.program,
      detail: "Program document current. All 10 required sections addressed.",
      subItems: [
        { label: "Written program exists and is accessible", ok: true },
        { label: "Program covers all 10 required sections", ok: true, link: "/hazcom-program" },
        { label: "Program is current (updated within 12 months)", ok: true },
      ],
    },
    {
      id: "2",
      item: "SDS Coverage",
      pass: sdsPct === 100,
      warn: sdsPct >= 90 && sdsPct < 100,
      score: Math.round(sdsScore * weights.sds),
      maxScore: weights.sds,
      detail: missingSdsChems.length === 0 && expiredSdsChems.length === 0
        ? `All ${totalSDS} SDS on file and current`
        : `${currentSDS} of ${totalSDS} SDS current \u2014 ${missingSdsChems.length} missing${expiredSdsChems.length > 0 ? `, ${expiredSdsChems.length} expired` : ""}`,
      subItems: [
        ...missingSdsChems.map((c) => ({
          label: `Missing SDS: ${c.product_name} (${c.location})`,
          ok: false,
          link: "/sds-library",
          fixDescription: `${c.product_name} SDS is missing \u2014 upload or request from ${c.manufacturer}`,
          fixAction: "Go to SDS Library",
        })),
        ...expiredSdsChems.map((c) => ({
          label: `Expired: ${c.product_name}`,
          ok: false,
          link: "/sds-library",
          fixDescription: `SDS is outdated \u2014 request current version from ${c.manufacturer}`,
          fixAction: "Go to SDS Library",
        })),
        ...(missingSdsChems.length === 0 && expiredSdsChems.length === 0
          ? [{ label: "All SDS documents are current and accessible", ok: true }]
          : []),
        { label: "SDS accessible on shop tablet at Station 1", ok: true },
        { label: "Offline backup cache functional", ok: true },
      ],
    },
    {
      id: "3",
      item: "Container Labeling",
      pass: labelPct === 100,
      warn: labelPct >= 80 && labelPct < 100,
      score: Math.round(labelScore * weights.labels),
      maxScore: weights.labels,
      detail: unlabeledChems.length === 0
        ? `All ${totalContainers} containers across ${new Set(chemicals.map((c) => c.location)).size} locations properly labeled`
        : `${labeledContainers} of ${totalContainers} containers labeled \u2014 ${unlabeledChems.length} chemical${unlabeledChems.length > 1 ? "s" : ""} need labels`,
      subItems: [
        ...unlabeledChems.map((c) => ({
          label: `${c.location}: ${c.product_name} (${c.container_count} ${c.container_type}, unlabeled)`,
          ok: false,
          link: "/labels",
          fixDescription: `Print GHS-compliant secondary container labels for ${c.product_name}`,
          fixAction: "Print Labels",
        })),
        ...(unlabeledChems.length === 0
          ? [{ label: "All secondary containers have GHS-compliant labels", ok: true }]
          : []),
        { label: "Shipped container labels intact and legible", ok: true },
      ],
    },
    {
      id: "4",
      item: "Employee Training",
      pass: trainingPct === 100,
      warn: trainingPct >= 80 && trainingPct < 100,
      score: Math.round(trainingScore * weights.training),
      maxScore: weights.training,
      detail: overdueEmployees.length === 0 && pendingEmployees.length === 0
        ? `All ${totalEmployees} employees current on required training`
        : `${fullyTrained} of ${totalEmployees} employees current${overdueEmployees.length > 0 ? ` \u2014 ${overdueEmployees.length} overdue` : ""}${pendingEmployees.length > 0 ? ` \u2014 ${pendingEmployees.length} pending` : ""}`,
      subItems: [
        ...overdueEmployees.map((e) => ({
          label: `Overdue: ${e.name} \u2014 ${e.pending_modules.join(", ") || "overdue modules"}`,
          ok: false,
          link: "/training",
          fixDescription: `Send training reminder or assign overdue courses`,
          fixAction: "Assign Training",
        })),
        ...pendingEmployees.map((e) => ({
          label: `Pending (new hire): ${e.name} \u2014 needs initial orientation`,
          ok: false,
          link: "/training",
          fixDescription: `New hire must complete HazCom orientation within 3 working days of start date`,
          fixAction: "Assign Training",
        })),
        ...(overdueEmployees.length === 0 && pendingEmployees.length === 0
          ? [{ label: "All employees have completed required training modules", ok: true }]
          : []),
        { label: "Training records maintained with digital acknowledgments", ok: true },
      ],
    },
    {
      id: "5",
      item: "Chemical Inventory",
      pass: true,
      warn: false,
      score: 0,
      maxScore: 0,
      detail: `${chemicals.length} chemicals tracked across ${new Set(chemicals.map((c) => c.location)).size} storage locations`,
      subItems: [
        { label: "All chemicals have matching product identifiers", ok: true },
        { label: `Inventory reconciled: ${chemicals.length} items verified`, ok: true },
        { label: "Storage locations properly identified and signed", ok: true },
      ],
    },
    {
      id: "6",
      item: "Multi-Employer Communication",
      pass: true,
      warn: false,
      score: weights.multiEmployer,
      maxScore: weights.multiEmployer,
      detail: "Contractor safety packet generation available via ShieldSDS",
      subItems: [
        { label: "Contractor Safety Packet template ready", ok: true },
        { label: "Packet includes relevant SDS, labeling info, and emergency procedures", ok: true },
        { label: "Digital acknowledgment capture available", ok: true },
      ],
    },
  ], [sdsPct, sdsScore, labelPct, labelScore, trainingPct, trainingScore, totalSDS, currentSDS, totalContainers, labeledContainers, totalEmployees, fullyTrained, chemicals, missingSdsChems, expiredSdsChems, unlabeledChems, overdueEmployees, pendingEmployees, weights.sds, weights.labels, weights.training, weights.program, weights.multiEmployer]);

  // Next action recommendation
  const nextAction = useMemo(() => {
    if (missingSdsChems.length > 0) return { text: `Upload missing SDS for ${missingSdsChems[0].product_name}`, link: "/sds-library" };
    if (overdueEmployees.length > 0) return { text: `Complete overdue training for ${overdueEmployees[0].name}`, link: "/training" };
    if (pendingEmployees.length > 0) return { text: `Complete new hire training for ${pendingEmployees[0].name}`, link: "/training" };
    if (unlabeledChems.length > 0) return { text: `Print labels for ${unlabeledChems[0].product_name}`, link: "/labels" };
    return null;
  }, [missingSdsChems, overdueEmployees, pendingEmployees, unlabeledChems]);

  // Audit log from live data
  const auditLog = useMemo(() => generateAuditLog(chemicals, employees), [chemicals, employees]);

  return (
    <DashboardLayout>
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="font-display font-black text-2xl text-white">Inspection Mode</h1>
          <p className="text-sm text-gray-400 mt-1">HazCom compliance audit and readiness report</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowShare(true)}
            className="flex items-center gap-2 bg-navy-800 border border-navy-700 hover:border-navy-600 text-gray-300 text-sm px-4 py-2 rounded-lg transition-colors"
          >
            <Link2 className="h-4 w-4" />
            Share Link
          </button>
          <button
            onClick={() => showToast("Export feature available with PDF generator module")}
            className="flex items-center gap-2 bg-amber-500 hover:bg-amber-400 text-navy-950 font-semibold text-sm px-4 py-2 rounded-lg transition-colors"
          >
            <Download className="h-4 w-4" />
            Export Packet
          </button>
        </div>
      </div>

      <div className="mb-6">
        <HelpCard>
          <p><strong className="text-white">During an OSHA HazCom inspection, the compliance officer evaluates your program against all requirements of 29 CFR 1910.1200.</strong></p>
          <p><strong className="text-amber-400">Opening Conference:</strong> Inspector explains why they&apos;re there. They ask to see your written HazCom program immediately.</p>
          <p><strong className="text-amber-400">Walkthrough:</strong> Inspector observes the workplace — Are containers labeled? Can employees access SDS? Are there unlabeled containers or chemicals without SDS?</p>
          <p><strong className="text-amber-400">Record Review:</strong> Inspector asks for chemical inventory list, training records, written program, and SDS for specific chemicals they observed.</p>
          <p><strong className="text-amber-400">Employee Interviews:</strong> Inspector may privately ask employees: &quot;Where do you find SDS?&quot; &quot;What would you do if this chemical got in your eyes?&quot; &quot;When were you last trained on chemical hazards?&quot;</p>
          <p>Your compliance score on this page reflects exactly what the inspector evaluates. Each Warning or Fail item is a potential citation. Fix them before an inspection — not during one.</p>
          <p><strong className="text-amber-400">Citation Penalties (current):</strong></p>
          <ul className="list-none space-y-1 ml-1">
            <li>&bull; Other-than-serious: up to <strong>$16,131</strong> per violation</li>
            <li>&bull; Serious: up to <strong>$16,131</strong> per violation</li>
            <li>&bull; Willful or repeated: up to <strong>$161,323</strong> per violation</li>
            <li>&bull; Failure to abate: up to <strong>$16,131</strong> per day</li>
          </ul>
        </HelpCard>
      </div>

      {/* Compliance Score + Info Row */}
      <div className="mb-8 bg-navy-900 border border-navy-700/50 rounded-xl p-6 flex items-center gap-8">
        {/* Ring */}
        <div className="relative flex-shrink-0">
          <svg className="h-36 w-36 -rotate-90" viewBox="0 0 120 120">
            <circle cx="60" cy="60" r="52" fill="none" stroke="#1A2D4D" strokeWidth="10" />
            <circle
              cx="60" cy="60" r="52" fill="none"
              stroke={readinessColor}
              strokeWidth="10" strokeLinecap="round"
              strokeDasharray={`${circumference * (score / 100)} ${circumference * (1 - score / 100)}`}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="font-display font-black text-3xl text-white">{score}%</span>
            <span className="text-xs text-gray-400">Compliant</span>
          </div>
        </div>

        {/* Details */}
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2">
            <ShieldCheck className={`h-6 w-6 ${score === 100 ? "text-status-green" : score >= 80 ? "text-status-amber" : "text-status-red"}`} />
            <h2 className="font-display font-bold text-xl text-white">{readinessLabel}</h2>
          </div>
          <p className="text-sm text-gray-400 max-w-lg">
            {failCount > 0
              ? `${failCount} category${failCount > 1 ? " categories" : ""} need${failCount === 1 ? "s" : ""} attention before your next inspection. Address the outstanding items to reach 100%.`
              : "All compliance checks passing. You are fully prepared for an OSHA inspection."}
          </p>
          {nextAction && (
            <Link href={nextAction.link} className="inline-flex items-center gap-1.5 mt-2 text-sm text-amber-400 hover:text-amber-300 transition-colors">
              <ArrowRight className="h-3.5 w-3.5" />
              Next: {nextAction.text}
            </Link>
          )}
          <div className="flex items-center gap-4 mt-3 text-xs text-gray-500">
            <div className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              Report generated: {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })} at {new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}
            </div>
            <div className="flex items-center gap-1">
              <MapPin className="h-3 w-3" />
              {shopInfo.name} &mdash; {shopInfo.address}, {shopInfo.city}, {shopInfo.state} {shopInfo.zip}
            </div>
          </div>
        </div>

        {/* Score Breakdown Mini */}
        <div className="flex-shrink-0 space-y-1.5 min-w-[160px]">
          <p className="text-xs text-gray-500 font-semibold uppercase tracking-wider mb-2">Score Breakdown</p>
          {[
            { label: "SDS Coverage", pct: Math.round(sdsScore * 100), weight: weights.sds },
            { label: "Labeling", pct: Math.round(labelScore * 100), weight: weights.labels },
            { label: "Training", pct: Math.round(trainingScore * 100), weight: weights.training },
            { label: "Written Program", pct: Math.round(programScore * 100), weight: weights.program },
            { label: "Multi-Employer", pct: Math.round(multiScore * 100), weight: weights.multiEmployer },
          ].map((item) => (
            <div key={item.label} className="flex items-center gap-2 text-xs">
              <span className="text-gray-400 w-24 truncate">{item.label}</span>
              <div className="flex-1 h-1.5 bg-navy-800 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full ${item.pct === 100 ? "bg-status-green" : item.pct >= 50 ? "bg-status-amber" : "bg-status-red"}`}
                  style={{ width: `${item.pct}%` }}
                />
              </div>
              <span className="text-gray-500 w-8 text-right">{item.weight}%</span>
            </div>
          ))}
        </div>
      </div>

      {/* Compliance Checklist */}
      <div className="mb-8">
        <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
          Compliance Checklist
        </h2>
        <div className="space-y-3">
          {checklist.map((item) => (
            <ChecklistCard key={item.id} item={item} />
          ))}
        </div>
      </div>

      {/* Audit Log */}
      <div>
        <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
          Audit Log
        </h2>
        <div className="bg-navy-900 border border-navy-700/50 rounded-xl overflow-hidden">
          {auditLog.length > 0 ? (
            auditLog.map((entry, i) => {
              const cat = getAuditCategory(entry.entry);
              const Icon = cat.icon;
              return (
                <div
                  key={i}
                  className={`flex items-start gap-4 px-5 py-3.5 hover:bg-navy-800/30 transition-colors ${
                    i < auditLog.length - 1 ? "border-b border-navy-700/30" : ""
                  }`}
                >
                  <div className="flex items-center gap-1 text-xs text-gray-500 whitespace-nowrap min-w-[100px]">
                    <Clock className="h-3 w-3 flex-shrink-0" />
                    {(() => {
                      try {
                        return new Date(entry.time).toLocaleDateString("en-US", { month: "short", day: "numeric" });
                      } catch {
                        return entry.time;
                      }
                    })()}
                  </div>
                  <div className="h-6 w-6 rounded-md bg-navy-800 flex items-center justify-center flex-shrink-0">
                    <Icon className={`h-3.5 w-3.5 ${cat.color}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-gray-300">{entry.entry}</p>
                  </div>
                </div>
              );
            })
          ) : (
            <div className="py-8 text-center text-gray-500 text-sm">No audit entries yet</div>
          )}
        </div>
      </div>

      {/* Modals & Toast */}
      {showShare && <ShareModal onClose={() => setShowShare(false)} onToast={(msg) => { setShowShare(false); showToast(msg); }} />}
      {toast && <Toast message={toast} onClose={() => setToast(null)} />}
    </DashboardLayout>
  );
}
