"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import DashboardLayout from "@/components/DashboardLayout";
import HelpCard from "@/components/HelpCard";
import SelfAuditWizard from "@/components/SelfAuditWizard";
import { generateInspectionPacketPDF } from "@/lib/pdf-export";
import {
  sdsEntries,
  inventoryItems,
  employees,
  trainingCourses,
  auditLog,
  shopInfo,
  programVersionHistory,
  selfAuditHistory,
  type SelfAuditResult,
} from "@/lib/data";
import {
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Download,
  Clock,
  ShieldCheck,
  ChevronDown,
  ChevronRight,
  FileText,
  Tags,
  GraduationCap,
  FlaskConical,
  BookOpen,
  Link2,
  X,
  ClipboardCheck,
  ArrowRight,
  Copy,
  MapPin,
  Send,
  History,
} from "lucide-react";

// ─── Audit log category detection ────────────────────────────────────────────

function getAuditCategory(entry: string): { icon: typeof FileText; color: string } {
  if (entry.includes("SDS")) return { icon: FileText, color: "text-blue-400" };
  if (entry.includes("Label") || entry.includes("label")) return { icon: Tags, color: "text-purple-400" };
  if (entry.includes("Training") || entry.includes("training")) return { icon: GraduationCap, color: "text-amber-400" };
  if (entry.includes("Program") || entry.includes("program")) return { icon: BookOpen, color: "text-emerald-400" };
  if (entry.includes("Chemical") || entry.includes("chemical") || entry.includes("Inventory") || entry.includes("inventory") || entry.includes("employee") || entry.includes("Employee")) return { icon: FlaskConical, color: "text-cyan-400" };
  return { icon: Clock, color: "text-gray-400" };
}

function parseAuditUser(entry: string): string {
  const match = entry.match(/\(([^)]+)\)/);
  if (match) return match[1];
  const nameMatch = entry.match(/:\s+([A-Z][a-z]+ [A-Z][a-z]+)/);
  if (nameMatch) return nameMatch[1];
  return "System";
}

// ─── Toast ────────────────────────────────────────────────────────────────────

function Toast({ message, onClose }: { message: string; onClose: () => void }) {
  return (
    <div className="fixed bottom-6 right-6 z-[60] bg-navy-800 border border-navy-600 rounded-xl px-5 py-3 flex items-center gap-3 shadow-2xl">
      <CheckCircle2 className="h-5 w-5 text-status-green flex-shrink-0" />
      <span className="text-sm text-white">{message}</span>
      <button onClick={onClose} className="text-gray-400 hover:text-white ml-2"><X className="h-4 w-4" /></button>
    </div>
  );
}

// ─── Share Modal ──────────────────────────────────────────────────────────────

function ShareModal({ onClose, onToast }: { onClose: () => void; onToast: (msg: string) => void }) {
  const [copied, setCopied] = useState(false);
  const [expiry, setExpiry] = useState("7d");
  const [accessMode, setAccessMode] = useState<"anyone" | "email">("anyone");
  const [restrictEmail, setRestrictEmail] = useState("");
  const shareId = "mikes-auto-body-2026-02-24";
  const mockUrl = `https://app.shieldsds.com/share/${shareId}`;
  const localUrl = `/share/${shareId}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(mockUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendEmail = () => {
    const subject = encodeURIComponent(`${shopInfo.name} — HazCom Compliance Report`);
    const body = encodeURIComponent(`Here is a read-only link to our HazCom compliance report:\n\n${mockUrl}\n\nThis link expires in ${expiry === "24h" ? "24 hours" : expiry === "7d" ? "7 days" : expiry === "30d" ? "30 days" : "never"}.\n\nGenerated by ShieldSDS`);
    const to = accessMode === "email" && restrictEmail ? restrictEmail : "";
    window.open(`mailto:${to}?subject=${subject}&body=${body}`, "_blank");
    onToast("Email client opened with share link");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-navy-900 border border-navy-700 rounded-2xl w-full max-w-md mx-4 shadow-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-navy-700">
          <h2 className="font-display font-bold text-lg text-white">Share Read-Only Link</h2>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-navy-800 text-gray-400 hover:text-white"><X className="h-5 w-5" /></button>
        </div>
        <div className="p-6 space-y-4">
          {/* URL */}
          <div>
            <label className="text-xs text-gray-400 uppercase tracking-wider font-semibold block mb-2">Shareable URL</label>
            <div className="flex items-center gap-2">
              <input type="text" readOnly value={mockUrl} className="flex-1 bg-navy-800 border border-navy-700 rounded-lg px-3 py-2 text-xs text-white font-mono" />
              <button onClick={handleCopy} className="flex items-center gap-1 bg-amber-500 hover:bg-amber-400 text-navy-950 font-semibold text-xs px-3 py-2 rounded-lg transition-colors">
                {copied ? <CheckCircle2 className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                {copied ? "Copied" : "Copy"}
              </button>
            </div>
            <a href={localUrl} target="_blank" rel="noopener noreferrer" className="text-[10px] text-amber-400 hover:text-amber-300 mt-1 inline-block">
              Preview the shared report &rarr;
            </a>
          </div>

          {/* Expiration */}
          <div>
            <label className="text-xs text-gray-400 uppercase tracking-wider font-semibold block mb-2">Link Expiration</label>
            <div className="flex gap-2">
              {[
                { label: "24 hours", value: "24h" },
                { label: "7 days", value: "7d" },
                { label: "30 days", value: "30d" },
                { label: "Never", value: "never" },
              ].map((opt) => (
                <button
                  key={opt.value}
                  onClick={() => setExpiry(opt.value)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                    expiry === opt.value
                      ? "bg-amber-500 text-navy-950"
                      : "bg-navy-800 text-gray-400 hover:text-white border border-navy-700"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          {/* Access Mode */}
          <div>
            <label className="text-xs text-gray-400 uppercase tracking-wider font-semibold block mb-2">Access</label>
            <div className="flex gap-2">
              <button
                onClick={() => setAccessMode("anyone")}
                className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                  accessMode === "anyone" ? "bg-amber-500 text-navy-950" : "bg-navy-800 text-gray-400 hover:text-white border border-navy-700"
                }`}
              >
                Anyone with link
              </button>
              <button
                onClick={() => setAccessMode("email")}
                className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                  accessMode === "email" ? "bg-amber-500 text-navy-950" : "bg-navy-800 text-gray-400 hover:text-white border border-navy-700"
                }`}
              >
                Email-restricted
              </button>
            </div>
            {accessMode === "email" && (
              <input
                type="email"
                value={restrictEmail}
                onChange={(e) => setRestrictEmail(e.target.value)}
                placeholder="recipient@example.com"
                className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg px-3 py-2 text-xs text-white placeholder-gray-500 focus:outline-none focus:border-amber-500/50"
              />
            )}
          </div>

          {/* Send via Email */}
          <button
            onClick={handleSendEmail}
            className="w-full flex items-center justify-center gap-2 bg-navy-800 border border-navy-700 hover:border-navy-600 text-gray-300 text-sm py-2.5 rounded-lg transition-colors"
          >
            <Send className="h-4 w-4" />
            Send via Email
          </button>

          <p className="text-xs text-gray-500">
            This link gives read-only access to the compliance report summary. No full SDS content or employee details are shared.
          </p>
        </div>
      </div>
    </div>
  );
}

// ─── Contractor Share Modal ───────────────────────────────────────────────────
// (Contractor shareable links are handled inline on the contractors page)

// ─── Expandable Checklist Item ────────────────────────────────────────────────

interface ChecklistItem {
  id: string;
  item: string;
  pass: boolean;
  warn: boolean;
  score: number;
  maxScore: number;
  detail: string;
  subItems: { label: string; ok: boolean; link?: string; fixDescription?: string; fixAction?: string }[];
}

function ChecklistCard({ item }: { item: ChecklistItem }) {
  const [expanded, setExpanded] = useState(!item.pass);

  const StatusIcon = item.pass
    ? CheckCircle2
    : item.warn
    ? AlertTriangle
    : XCircle;
  const statusColor = item.pass
    ? "text-status-green"
    : item.warn
    ? "text-status-amber"
    : "text-status-red";
  const borderColor = item.pass
    ? "border-navy-700/50"
    : item.warn
    ? "border-status-amber/30"
    : "border-status-red/30";
  const badgeClass = item.pass
    ? "bg-status-green/15 text-status-green"
    : item.warn
    ? "bg-status-amber/15 text-status-amber"
    : "bg-status-red/15 text-status-red";
  const badgeText = item.pass ? "Pass" : item.warn ? "Warning" : "Fail";

  return (
    <div className={`bg-navy-900 border rounded-xl transition-colors ${borderColor}`}>
      <button
        className="w-full flex items-center justify-between p-5 text-left"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-3 flex-1 min-w-0">
          <StatusIcon className={`h-5 w-5 ${statusColor} flex-shrink-0`} />
          <div className="flex-1 min-w-0">
            <h3 className="text-sm font-medium text-white">{item.item}</h3>
            <p className="text-xs text-gray-400 mt-0.5">{item.detail}</p>
          </div>
        </div>
        <div className="flex items-center gap-3 flex-shrink-0 ml-4">
          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${badgeClass}`}>
            {badgeText}
          </span>
          {expanded ? <ChevronDown className="h-4 w-4 text-gray-400" /> : <ChevronRight className="h-4 w-4 text-gray-400" />}
        </div>
      </button>
      {expanded && item.subItems.length > 0 && (
        <div className="px-5 pb-5 pt-0">
          <div className="border-t border-navy-700/30 pt-3 space-y-2">
            {item.subItems.map((sub, i) => (
              <div key={i} className="text-xs">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {sub.ok ? (
                      <CheckCircle2 className="h-3.5 w-3.5 text-status-green" />
                    ) : (
                      <XCircle className="h-3.5 w-3.5 text-status-red" />
                    )}
                    <span className={sub.ok ? "text-gray-400" : "text-white"}>{sub.label}</span>
                  </div>
                  {sub.link && !sub.ok && (
                    <Link href={sub.link} className="flex items-center gap-1 text-amber-400 hover:text-amber-300 transition-colors whitespace-nowrap ml-2">
                      {sub.fixAction || "Fix"} <ArrowRight className="h-3 w-3" />
                    </Link>
                  )}
                </div>
                {sub.fixDescription && !sub.ok && (
                  <p className="text-gray-500 ml-5.5 mt-0.5 pl-[22px]">{sub.fixDescription}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Main Page ───────────────────────────────────────────────────────────────

export default function InspectionPage() {
  const [toast, setToast] = useState<string | null>(null);
  const [showShare, setShowShare] = useState(false);
  const [showAudit, setShowAudit] = useState(false);
  const [audits, setAudits] = useState<SelfAuditResult[]>(selfAuditHistory);
  const [showAuditHistory, setShowAuditHistory] = useState(false);

  // ── Dynamic compliance calculations ──────────────────────────────────────

  const totalSDS = sdsEntries.length;
  const currentSDS = sdsEntries.filter((s) => s.sdsStatus === "current").length;
  const missingSdsEntries = sdsEntries.filter((s) => s.sdsStatus === "missing");
  const reviewSdsEntries = sdsEntries.filter((s) => s.sdsStatus === "review");

  const totalContainers = inventoryItems.reduce((sum, i) => sum + i.containers, 0);
  const labeledContainers = inventoryItems.filter((i) => i.labeled).reduce((sum, i) => sum + i.containers, 0);
  const unlabeledItems = inventoryItems.filter((i) => !i.labeled);
  const labelPct = totalContainers > 0 ? Math.round((labeledContainers / totalContainers) * 100) : 100;

  const totalEmployees = employees.length;
  const fullyTrained = employees.filter((e) => e.status === "current").length;
  const overdueEmployees = employees.filter((e) => e.status === "overdue");
  const pendingEmployees = employees.filter((e) => e.status === "pending");
  const trainingPct = totalEmployees > 0 ? Math.round((fullyTrained / totalEmployees) * 100) : 100;

  const sdsPct = totalSDS > 0 ? Math.round((currentSDS / totalSDS) * 100) : 100;

  // ── Weighted score calculation ──────────────────────────────────────────

  const weights = { sds: 25, labels: 25, training: 25, program: 15, multiEmployer: 10 };

  const sdsScore = sdsPct === 100 ? 1 : sdsPct >= 90 ? 0.5 : 0;
  const labelScore = labelPct === 100 ? 1 : labelPct >= 80 ? 0.5 : 0;
  const trainingScore = trainingPct === 100 ? 1 : trainingPct >= 80 ? 0.5 : 0;
  const programScore = 1; // Written HazCom Program exists
  const multiScore = 1; // Contractor pack generation available

  const score = Math.round(
    sdsScore * weights.sds +
    labelScore * weights.labels +
    trainingScore * weights.training +
    programScore * weights.program +
    multiScore * weights.multiEmployer
  );

  const circumference = 2 * Math.PI * 52;
  const failCount = [sdsScore, labelScore, trainingScore, programScore, multiScore].filter((s) => s < 1).length;
  const readinessLabel = score === 100 ? "Fully Ready" : score >= 80 ? "Mostly Ready" : "Needs Work";
  const readinessColor = score === 100 ? "#34C759" : score >= 80 ? "#F5A623" : "#FF3B30";

  // ── Build checklist items ───────────────────────────────────────────────

  const checklist: ChecklistItem[] = useMemo(() => [
    {
      id: "1",
      item: "Written HazCom Program",
      pass: true,
      warn: false,
      score: weights.program,
      maxScore: weights.program,
      detail: `Program document current \u2014 version ${programVersionHistory[0].version}. Last updated ${new Date(programVersionHistory[0].date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}.`,
      subItems: [
        { label: "Written program exists and is accessible", ok: true },
        { label: "Program covers all 10 required sections", ok: true, link: "/hazcom-program" },
        { label: "Program is current (updated within 12 months)", ok: true },
      ],
    },
    {
      id: "2",
      item: "SDS Coverage",
      pass: sdsPct === 100,
      warn: sdsPct >= 90 && sdsPct < 100,
      score: Math.round(sdsScore * weights.sds),
      maxScore: weights.sds,
      detail: missingSdsEntries.length === 0
        ? `All ${totalSDS} SDS on file and current`
        : `${currentSDS} of ${totalSDS} SDS current \u2014 ${missingSdsEntries.length} missing${reviewSdsEntries.length > 0 ? `, ${reviewSdsEntries.length} need review` : ""}`,
      subItems: [
        ...missingSdsEntries.map((s) => ({
          label: `Missing SDS: ${s.productName} (${s.storageLocation})`,
          ok: false,
          link: "/sds-library",
          fixDescription: `${s.productName} SDS is missing — upload or request from ${s.manufacturer}`,
          fixAction: "Go to SDS Library",
        })),
        ...reviewSdsEntries.map((s) => ({
          label: `Review needed: ${s.productName}`,
          ok: false,
          link: "/sds-library",
          fixDescription: `SDS revision is outdated — request current version from ${s.manufacturer}`,
          fixAction: "Go to SDS Library",
        })),
        ...(missingSdsEntries.length === 0 && reviewSdsEntries.length === 0
          ? [{ label: "All SDS documents are current and accessible", ok: true }]
          : []),
        { label: `SDS accessible on shop tablet at Station 1`, ok: true },
        { label: `Offline backup cache functional`, ok: true },
      ],
    },
    {
      id: "3",
      item: "Container Labeling",
      pass: labelPct === 100,
      warn: labelPct >= 80 && labelPct < 100,
      score: Math.round(labelScore * weights.labels),
      maxScore: weights.labels,
      detail: unlabeledItems.length === 0
        ? `All ${totalContainers} containers across ${new Set(inventoryItems.map((i) => i.location)).size} locations properly labeled`
        : `${labeledContainers} of ${totalContainers} containers labeled \u2014 ${unlabeledItems.length} item${unlabeledItems.length > 1 ? "s" : ""} need labels`,
      subItems: [
        ...unlabeledItems.map((i) => ({
          label: `${i.location}: ${i.product} (${i.containers} containers, unlabeled)`,
          ok: false,
          link: "/labels",
          fixDescription: `Print GHS-compliant secondary container labels for ${i.product}`,
          fixAction: "Print Labels",
        })),
        ...(unlabeledItems.length === 0
          ? [{ label: "All secondary containers have GHS-compliant labels", ok: true }]
          : []),
        { label: "Shipped container labels intact and legible", ok: true },
      ],
    },
    {
      id: "4",
      item: "Employee Training",
      pass: trainingPct === 100,
      warn: trainingPct >= 80 && trainingPct < 100,
      score: Math.round(trainingScore * weights.training),
      maxScore: weights.training,
      detail: overdueEmployees.length === 0 && pendingEmployees.length === 0
        ? `All ${totalEmployees} employees current on required training`
        : `${fullyTrained} of ${totalEmployees} employees current${overdueEmployees.length > 0 ? ` \u2014 ${overdueEmployees.length} overdue` : ""}${pendingEmployees.length > 0 ? ` \u2014 ${pendingEmployees.length} pending` : ""}`,
      subItems: [
        ...overdueEmployees.map((e) => {
          const overdueCourses = e.trainings
            .filter((t) => t.status === "overdue")
            .map((t) => trainingCourses.find((c) => c.id === t.courseId)?.title)
            .filter(Boolean);
          return {
            label: `Overdue: ${e.name} \u2014 ${overdueCourses.join(", ")}`,
            ok: false,
            link: "/training",
            fixDescription: `Send training reminder or assign ${overdueCourses.length} overdue course${overdueCourses.length > 1 ? "s" : ""}`,
            fixAction: "Assign Training",
          };
        }),
        ...pendingEmployees.map((e) => ({
          label: `Pending (new hire): ${e.name} \u2014 needs initial orientation`,
          ok: false,
          link: "/training",
          fixDescription: `New hire must complete HazCom orientation within 3 working days of start date`,
          fixAction: "Assign Training",
        })),
        ...(overdueEmployees.length === 0 && pendingEmployees.length === 0
          ? [{ label: "All employees have completed required training modules", ok: true }]
          : []),
        { label: "Training records maintained with digital acknowledgments", ok: true },
      ],
    },
    {
      id: "5",
      item: "Chemical Inventory",
      pass: true,
      warn: false,
      score: 0,
      maxScore: 0,
      detail: `${inventoryItems.length} chemicals tracked across ${new Set(inventoryItems.map((i) => i.location)).size} storage locations`,
      subItems: [
        { label: "All chemicals have matching product identifiers", ok: true },
        { label: `Inventory reconciled: ${inventoryItems.length} items verified`, ok: true },
        { label: "Storage locations properly identified and signed", ok: true },
      ],
    },
    {
      id: "6",
      item: "Multi-Employer Communication",
      pass: true,
      warn: false,
      score: weights.multiEmployer,
      maxScore: weights.multiEmployer,
      detail: "Contractor safety packet generation available via ShieldSDS",
      subItems: [
        { label: "Contractor Safety Packet template ready", ok: true },
        { label: "Packet includes relevant SDS, labeling info, and emergency procedures", ok: true },
        { label: "Digital acknowledgment capture available", ok: true },
      ],
    },
  // eslint-disable-next-line react-hooks/exhaustive-deps
  ], [sdsPct, sdsScore, labelPct, labelScore, trainingPct, trainingScore, programScore, currentSDS, totalSDS, totalContainers, labeledContainers, totalEmployees, fullyTrained, missingSdsEntries, reviewSdsEntries, unlabeledItems, overdueEmployees, pendingEmployees, weights.sds, weights.labels, weights.training, weights.program, weights.multiEmployer]);

  // Find highest priority incomplete item for recommendation
  const nextAction = useMemo(() => {
    if (missingSdsEntries.length > 0) return { text: `Upload missing SDS for ${missingSdsEntries[0].productName}`, link: "/sds-library" };
    if (overdueEmployees.length > 0) return { text: `Complete overdue training for ${overdueEmployees[0].name}`, link: "/training" };
    if (pendingEmployees.length > 0) return { text: `Complete new hire training for ${pendingEmployees[0].name}`, link: "/training" };
    if (unlabeledItems.length > 0) return { text: `Print labels for ${unlabeledItems[0].product}`, link: "/labels" };
    return null;
  }, [missingSdsEntries, overdueEmployees, pendingEmployees, unlabeledItems]);

  return (
    <DashboardLayout>
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="font-display font-black text-2xl text-white">Inspection Mode</h1>
          <p className="text-sm text-gray-400 mt-1">HazCom compliance audit and readiness report</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowAudit(true)}
            className="flex items-center gap-2 bg-navy-800 border border-navy-700 hover:border-navy-600 text-gray-300 text-sm px-4 py-2 rounded-lg transition-colors"
          >
            <ClipboardCheck className="h-4 w-4" />
            Run Self-Audit
          </button>
          <button
            onClick={() => setShowShare(true)}
            className="flex items-center gap-2 bg-navy-800 border border-navy-700 hover:border-navy-600 text-gray-300 text-sm px-4 py-2 rounded-lg transition-colors"
          >
            <Link2 className="h-4 w-4" />
            Share Link
          </button>
          <button
            onClick={() => { setToast("Generating PDF\u2026"); generateInspectionPacketPDF().then(() => setToast("Inspection packet PDF downloaded")).catch(() => setToast("PDF generation failed")); }}
            className="flex items-center gap-2 bg-amber-500 hover:bg-amber-400 text-navy-950 font-semibold text-sm px-4 py-2 rounded-lg transition-colors"
          >
            <Download className="h-4 w-4" />
            Export Packet
          </button>
        </div>
      </div>

      <div className="mb-6">
        <HelpCard>
          <p>
            <strong className="text-amber-400">OSHA 29 CFR 1910.1200(e)</strong> requires employers to maintain a written hazard communication program. Regular self-audits using this inspection checklist help identify gaps before an OSHA inspector does. Non-compliance can result in citations averaging $16,131 per violation.
          </p>
        </HelpCard>
      </div>

      {/* Compliance Score + Info Row */}
      <div className="mb-8 bg-navy-900 border border-navy-700/50 rounded-xl p-6 flex items-center gap-8">
        {/* Ring */}
        <div className="relative flex-shrink-0">
          <svg className="h-36 w-36 -rotate-90" viewBox="0 0 120 120">
            <circle cx="60" cy="60" r="52" fill="none" stroke="#1A2D4D" strokeWidth="10" />
            <circle
              cx="60" cy="60" r="52" fill="none"
              stroke={readinessColor}
              strokeWidth="10" strokeLinecap="round"
              strokeDasharray={`${circumference * (score / 100)} ${circumference * (1 - score / 100)}`}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="font-display font-black text-3xl text-white">{score}%</span>
            <span className="text-xs text-gray-400">Compliant</span>
          </div>
        </div>

        {/* Details */}
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2">
            <ShieldCheck className={`h-6 w-6 ${score === 100 ? "text-status-green" : score >= 80 ? "text-status-amber" : "text-status-red"}`} />
            <h2 className="font-display font-bold text-xl text-white">{readinessLabel}</h2>
          </div>
          <p className="text-sm text-gray-400 max-w-lg">
            {failCount > 0
              ? `${failCount} category${failCount > 1 ? " categories" : ""} need${failCount === 1 ? "s" : ""} attention before your next inspection. Address the outstanding items to reach 100%.`
              : "All compliance checks passing. You are fully prepared for an OSHA inspection."}
          </p>
          {nextAction && (
            <Link href={nextAction.link} className="inline-flex items-center gap-1.5 mt-2 text-sm text-amber-400 hover:text-amber-300 transition-colors">
              <ArrowRight className="h-3.5 w-3.5" />
              Next: {nextAction.text}
            </Link>
          )}
          <div className="flex items-center gap-4 mt-3 text-xs text-gray-500">
            <div className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              Report generated: {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })} at {new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}
            </div>
            <div className="flex items-center gap-1">
              <MapPin className="h-3 w-3" />
              {shopInfo.name} &mdash; {shopInfo.address}, {shopInfo.city}, {shopInfo.state} {shopInfo.zip}
            </div>
          </div>
        </div>

        {/* Score Breakdown Mini */}
        <div className="flex-shrink-0 space-y-1.5 min-w-[160px]">
          <p className="text-xs text-gray-500 font-semibold uppercase tracking-wider mb-2">Score Breakdown</p>
          {[
            { label: "SDS Coverage", pct: Math.round(sdsScore * 100), weight: weights.sds },
            { label: "Labeling", pct: Math.round(labelScore * 100), weight: weights.labels },
            { label: "Training", pct: Math.round(trainingScore * 100), weight: weights.training },
            { label: "Written Program", pct: Math.round(programScore * 100), weight: weights.program },
            { label: "Multi-Employer", pct: Math.round(multiScore * 100), weight: weights.multiEmployer },
          ].map((item) => (
            <div key={item.label} className="flex items-center gap-2 text-xs">
              <span className="text-gray-400 w-24 truncate">{item.label}</span>
              <div className="flex-1 h-1.5 bg-navy-800 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full ${item.pct === 100 ? "bg-status-green" : item.pct >= 50 ? "bg-status-amber" : "bg-status-red"}`}
                  style={{ width: `${item.pct}%` }}
                />
              </div>
              <span className="text-gray-500 w-8 text-right">{item.weight}%</span>
            </div>
          ))}
        </div>
      </div>

      {/* Compliance Checklist */}
      <div className="mb-8">
        <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
          Compliance Checklist
        </h2>
        <div className="space-y-3">
          {checklist.map((item) => (
            <ChecklistCard key={item.id} item={item} />
          ))}
        </div>
      </div>

      {/* Previous Self-Audits */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider">Previous Self-Audits</h2>
          <button
            onClick={() => setShowAuditHistory(!showAuditHistory)}
            className="text-xs text-amber-400 hover:text-amber-300 flex items-center gap-1 transition-colors"
          >
            <History className="h-3.5 w-3.5" />
            {showAuditHistory ? "Collapse" : "Show All"}
          </button>
        </div>
        <div className="space-y-2">
          {(showAuditHistory ? audits : audits.slice(0, 2)).map((audit) => {
            const scoreColor = audit.score >= 90 ? "text-status-green" : audit.score >= 70 ? "text-status-amber" : "text-status-red";
            const unresolvedCount = audit.findings.filter((f) => !f.resolved).length;
            return (
              <div key={audit.id} className="bg-navy-900 border border-navy-700/50 rounded-xl p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2">
                      <ClipboardCheck className="h-4 w-4 text-gray-500" />
                      <span className="text-sm text-white font-medium">
                        {new Date(audit.date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                      </span>
                    </div>
                    <span className={`font-display font-bold text-lg ${scoreColor}`}>{audit.score}%</span>
                    <span className="text-xs text-gray-500">by {audit.auditor}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    {unresolvedCount > 0 && (
                      <span className="text-xs bg-status-red/15 text-status-red px-2 py-0.5 rounded-full font-medium">
                        {unresolvedCount} unresolved
                      </span>
                    )}
                    <span className="text-xs text-gray-500">{audit.findings.length} finding{audit.findings.length !== 1 ? "s" : ""}</span>
                  </div>
                </div>
                {audit.findings.length > 0 && (
                  <div className="mt-3 grid grid-cols-2 gap-1.5">
                    {audit.findings.map((f, j) => (
                      <div key={j} className="flex items-center gap-1.5 text-xs">
                        {f.resolved ? (
                          <CheckCircle2 className="h-3 w-3 text-status-green flex-shrink-0" />
                        ) : (
                          <XCircle className="h-3 w-3 text-status-red flex-shrink-0" />
                        )}
                        <span className={f.resolved ? "text-gray-500 line-through" : "text-gray-300"}>{f.issue}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Audit Log */}
      <div>
        <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
          Audit Log
        </h2>
        <div className="bg-navy-900 border border-navy-700/50 rounded-xl overflow-hidden">
          {auditLog.map((entry, i) => {
            const cat = getAuditCategory(entry.entry);
            const Icon = cat.icon;
            const user = parseAuditUser(entry.entry);
            return (
              <div
                key={i}
                className={`flex items-start gap-4 px-5 py-3.5 hover:bg-navy-800/30 transition-colors ${
                  i < auditLog.length - 1 ? "border-b border-navy-700/30" : ""
                }`}
              >
                <div className="flex items-center gap-1 text-xs text-gray-500 whitespace-nowrap min-w-[180px]">
                  <Clock className="h-3 w-3 flex-shrink-0" />
                  {entry.time}
                </div>
                <div className={`h-6 w-6 rounded-md bg-navy-800 flex items-center justify-center flex-shrink-0`}>
                  <Icon className={`h-3.5 w-3.5 ${cat.color}`} />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-gray-300">{entry.entry}</p>
                </div>
                <span className="text-xs text-gray-500 flex-shrink-0 whitespace-nowrap">{user}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* Modals & Toast */}
      {showShare && <ShareModal onClose={() => setShowShare(false)} onToast={(msg) => { setShowShare(false); setToast(msg); }} />}
      <SelfAuditWizard
        open={showAudit}
        onClose={() => setShowAudit(false)}
        onComplete={({ score: auditScore, findings: auditFindings }) => {
          const newAudit: SelfAuditResult = {
            id: `audit-${audits.length + 1}`,
            date: new Date().toISOString().split("T")[0],
            score: auditScore,
            checkedCount: 0,
            totalItems: 0,
            findings: auditFindings.map((f) => ({ area: f.split(":")[0] || "General", issue: f, resolved: false })),
            auditor: shopInfo.owner,
          };
          setAudits((prev) => [newAudit, ...prev]);
          setToast(`Self-audit saved — score: ${auditScore}%`);
        }}
      />
      {toast && <Toast message={toast} onClose={() => setToast(null)} />}
    </DashboardLayout>
  );
}
